:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= CLI: First Time Login

The default and recommended method for interacting with the Openshift Container Platform is with the `oc` command.  In limited circumstances you could be directed to use other tools to invoke action or retrieve data from OCP, but for the most part all of your acitivities will be with `oc`.

== Login to OCP Cluster

=== Verify Your Credentials

Since you probably just completed the installation steps, you are more than likely already signed on with the proper credentials.  If you are not the user *root* on the *workstation* host, use the steps outlined in link:Getting-Started.adoc[Getting Started]  to get signed on.

.[root@workstation ~]#
----
uname -n

whoami
----

.Your output should look like this
[source,indent=4]
----
workstation.example.com

root
----

Your workshop environment is preconfigured with distributed ssh-keys to ease the management of sessions from one host to another.  As the user *root* on the host *workstation* you can easily sign-on to any host in your cluster using `ssh`.

=== Connect to host master.example.com

As mentioned, ssh keys have been distributed within the cluster to allow seemless connections without requiring the constant prompting for passwords.  If you are being prompted then it is likely that you are not an established `root` user session.

Proceed to connect to host *master*.

.[root@workstation ~]#
----    
ssh master
----

=== Login as *admin* to OCP Cluster

First order of business is to sign-on to the Openshift platform.  This is accomplished as follows.

.[root@master ~]# 
----
oc login -u admin
----

.Key-Values for Login
[horizontal]
*Username*:: admin
*Password*:: redhat

You can verify what credentials the current 'oc' session is using with `oc whoami`

.[root@master ~]# 
----
oc whoami
----

.Your output should look like this
[source,indent=4]
----
admin                                                                                 
----

Now that you have logged in to Openshift using the *oc* command, you are ready to start interacting with the Openshift Container Platfrom.  This session will remain active until it expires.  
        
[discrete]
== End of Unit

*Next:* link:CLI-Hello-World.adoc[OCP CLI: Hello-World]

link:../OCP-Workshop.adoc#toc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
    
