:sectnums:
:sectnumlevels: 2
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:toc:

= Understanding Variables and Secrets

*Source Code:* link:https://github.com/xtophd/OCP-Workshop/blob/master/src/bluegreen/index.php[index.php]

== Prepare the Application



=== Create a Project

.[root@master ~]#
----
oc new-project bluegreen --description="Example with ENV VARs" --display-name="Blue Green"
----

=== Deploy an Image

We are going to create 2 applications using the same source.  One will be called "watcher" and the other "worker"

.[root@master ~]#
----
oc new-app registry.access.redhat.com/rhscl/php-71-rhel7~https://github.com/xtophd/OCP-Workshop --context-dir=/src/bluegreen --name=watcher

oc new-app registry.access.redhat.com/rhscl/php-71-rhel7~https://github.com/xtophd/OCP-Workshop --context-dir=/src/bluegreen --name=worker

oc logs -f bc/worker

oc logs -f bc/watcher
----

At this point we've deployed 2 applications which do nothing.  They will need additional configuration to activate.

=== Expose a Route

.[root@master ~]#
----
oc expose service watcher --hostname=watcher.cloud.example.com

oc expose service worker  --hostname=worker.cloud.example.com
----

== Environment Variables

Openshift environment variables are a means to pass key/value pairs from the underlying host to the processess in the container.  Variables can provide configuration data, credentials and more.

=== Add Env Vars to Build Configs

.[root@master ~]#
----
oc env dc/worker myMode=worker myColor=blue

curl http://worker.cloud.example.com
----

.[root@master ~]#
----
oc env dc/watcher myMode=watcher myRoute=http://worker.cloud.example.com
----

=== Scale up 'worker' pods

.[root@master ~]#
----
oc scale --replicas=3 dc/worker

oc get pods -o wide
----

=== Change Env Vars in Build Configs

.[root@master ~]#
----
oc env dc/worker myColor=green

curl http://worker.cloud.example.com
----





== Secrets

Secrets decouple sensitive content from the pods that use it.  They can be mounted into containers using a volume plug-in or used by the system to perform actions on behalf of a pod. 

=== Create a Secret

=== Add Secret to Build Configs

=== Consumig Secrets in Pods

== Deployments

=== View Available Revisions

Retreve general revision history

.[root@master ~]#
----
oc rollout history dc/worker
----

=== View Specific Revision Details

.[root@master ~]#
----
oc rollout history dc/worker --revision=2
----

=== Rolling Back Changes

.[root@master ~]#
----
oc rollback dc/worker
----

=== Strategies

A deployment strategy is an algorithym which is implemented when changing or upgrading an application. The goal is to invoke change whilst reducing downtime or disruption to the end user.

There are 3 fundamental strategies for rollouts:

  . *Rolling*: slowly replaces previous version of an application with instances of the new version.  Uses parameters like *masSurge* and *maxUnavailable* (among others) to control rolling behaviour. Use when: you don't want downtime, app supports old code and new code coexisting for a brief period.
  . *Recreate*: scales down previous deployment to zero, then scales up the new deployment.  Uses additional pre/mid/post-lifecycle hooks to customize.  Use when: outside tasks are necessart (ie: migrations), incompatabilities between versions, volumes are used which cannot be shared.
  . *Custom*: provide your own deployment behaviour.  

The WebUI provides a relatively simple interface to modifying a strategy and it's accompanying parameters.  From the command-line, we are currently left with `oc edit` or `oc patch`

=== Scale Up Number of Workers

To get a better sense of how deployments updates, let us add a few more pods to the deployment

.[root@master ~]#
----
oc scale --replicas=10 dc/worker
----

=== Watch a Rolling Update





=== Change the Deployment Strategy

.[root@master ~]#
----
oc patch dc/worker --patch '{"spec":{"strategy":{"type":"Recreate"}}}'
----

=== Watch a Recreate Update




== EXTRA STUFF

=== List variables for a POD

oc set env pod/p1 --list

=== Trigger a fresh build after source edit

oc start-build bc/worker
oc logs -f bc/worker

=== emptyDir for image caching volume

=== mysql DB for history/trending

[discrete]
== End of Unit

link:../OCP-Workshop.adoc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
