:sectnums:
:sectnumlevels: 2
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:toc:

= CLI: Blue Green Deployments

In this unit, we will use a simple PHP based application to simulate and observe an application deployment, scaling adjustments and updates under different scenarios.  Topics covered will include: 

  . Environment Variables,
  . Secrets,
  . Application Scaling,
  . Rollbacks,
  . Deployment Strategies, and
  . Blue Green Updates using Routes

Take a moment to review the source for this exercise.  It is NOT very complicated.

    *Source Code:* link:https://github.com/xtophd/OCP-Workshop/blob/master/src/bluegreen/index.php[index.php]

This application uses a single code base to execute 2 different activities.  If left unconfigured, the application is "Idle".  Once configured the application is either a "Worker" or a "Watcher".  So the basic premise of this exercise is to deploy the same code base in 2 different Openshift applications and then configure one as a "Worker" and the other as a "Watcher".

Let's get started by repeating the 6 typical steps of deploying and application:

  . *Credentials:* oc login
  . *Create a Project:* oc new project 
  . *Deploy an Image:* oc new-app
  . *Expose a Route:* oc expose
  . *Modify the Project, Build or Deployment*
  . *Validation*

== Initial Deployment of Blue Green

=== Credentials

NOTE: If you are continuing work from previous workshop exercises, chances are you can skip right to the nixt section.

Ensure you are signed on to the `master.example.com` host as the user `root`.  Also ensure that your openshift crendential is `admin`.

.[root@workstation ~]#
----
ssh master.example.com
----

.[root@master ~]# 
----
oc whoami
----

.Your output should look like this
[source,indent=4]
----
admin                                                                                 
----

If you are NOT signed in as `admin`, proceed to sign-on to Openshift.

.Key-Values for Login
[horizontal]
*Username*:: admin
*Password*:: redhat

.[root@master ~]#
----
oc login -u admin
----

=== Create a Project

.[root@master ~]#
----
oc new-project bluegreen --description="Workshop Blue Green Exercise" --display-name="Blue Green"
----

=== Deploy an Image

As mentioned, we are going to create 2 applications using the same source.  One will be called "watcher" and the other "worker"

.[root@master ~]#
----
oc new-app registry.access.redhat.com/rhscl/php-71-rhel7~https://github.com/xtophd/OCP-Workshop --context-dir=/src/bluegreen --name=watcher

oc new-app registry.access.redhat.com/rhscl/php-71-rhel7~https://github.com/xtophd/OCP-Workshop --context-dir=/src/bluegreen --name=worker
----

We will pause here until the applications are built.  

.[root@master ~]#
----
oc logs -f bc/watcher
----

At this point we've deployed 2 applications which do nothing and report themselves as "Idle".

=== Expose a Route

.[root@master ~]#
----
oc expose service watcher --hostname=watcher.cloud.example.com

oc expose service worker  --hostname=worker.cloud.example.com
----

== Environment Variables

Openshift environment variables are a means to pass key/value pairs from the underlying host to the processess in the container.  Variables can provide configuration data, credentials and more.

=== Add Env Vars to Build Configs

.[root@master ~]#
----
oc env dc/worker myMode=worker myColor=blue

curl http://worker.cloud.example.com
----

.[root@master ~]#
----
oc env dc/watcher myMode=watcher myRoute=http://worker.cloud.example.com
----

=== Scale up 'worker' pods

.[root@master ~]#
----
oc scale --replicas=3 dc/worker
----

.[root@master ~]#
----
oc get pods -o wide
----

.[root@master ~]#
----
lynx -d http://watcher.cloud.example.com
----

=== Change Env Vars in Build Configs

.[root@master ~]#
----
oc env dc/worker myColor=green
----

.[root@master ~]#
----
watch lynx -d http://watcher.cloud.example.com
----

.[root@master ~]#
----
oc scale --replicas=10 dc/worker
----

.[root@master ~]#
----
watch lynx -d http://watcher.cloud.example.com
----

.[root@master ~]#
----
oc env dc/worker myColor=blue
----

.[root@master ~]#
----
watch lynx -d http://watcher.cloud.example.com
----

== Secrets

Secrets decouple sensitive content from the pods that use it.  They can be mounted into containers using a volume plug-in or used by the system to perform actions on behalf of a pod. 

=== Create a Secret

=== Add Secret to Build Configs

=== Consumig Secrets in Pods

== Deployments

=== View Available Revisions

Retreve general revision history

.[root@master ~]#
----
oc rollout history dc/worker
----

=== Rollbacks

==== View Revision History

.[root@master ~]#
----
oc rollout history dc/worker --revision=2
----

==== View Specific Revision Details

.[root@master ~]#
----
oc rollout history dc/worker --revision=2
----

==== Rolling Back Changes

.[root@master ~]#
----
oc rollback dc/worker
----

=== Strategies

A deployment strategy is an algorithym which is implemented when changing or upgrading an application. The goal is to invoke change whilst reducing downtime or disruption to the end user.

There are 3 fundamental strategies for rollouts:

  . *Rolling*: slowly replaces previous version of an application with instances of the new version.  Uses parameters like *masSurge* and *maxUnavailable* (among others) to control rolling behaviour. Use when: you don't want downtime, app supports old code and new code coexisting for a brief period.
  . *Recreate*: scales down previous deployment to zero, then scales up the new deployment.  Uses additional pre/mid/post-lifecycle hooks to customize.  Use when: outside tasks are necessart (ie: migrations), incompatabilities between versions, volumes are used which cannot be shared.
  . *Custom*: provide your own deployment behaviour.  

The WebUI provides a relatively simple interface to modifying a strategy and it's accompanying parameters.  From the command-line, we are currently left with `oc edit` or `oc patch`

=== Scale Up Number of Workers

To get a better sense of how deployments update, let us add a few more pods to the deployment

.[root@master ~]#
----
oc scale --replicas=20 dc/worker
----

=== Watch a Rolling Update





=== Change the Deployment Strategy

.[root@master ~]#
----
oc patch dc/worker --patch '{"spec":{"strategy":{"type":"Recreate"}}}'
----

=== Watch a Recreate Update




== EXTRA STUFF

=== List variables for a POD

oc set env pod/p1 --list

=== Trigger a fresh build after source edit

oc start-build bc/worker
oc logs -f bc/worker

=== emptyDir for image caching volume

=== mysql DB for history/trending

[discrete]
== End of Unit

link:../OCP-Workshop.adoc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
