:gitrepo: https://github.com/xtophd/OCP-Workshop
:includedir: _includes
:doctype: book
:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Getting Started

[discrete]
== Additional Reference Materials

NOTE: You are not required to reference outside documentation for these exercises.  This is informational only.

Red Hat's official documentation can be found publicly with the links provided below.  It is important to note that this workshop guide supports a very narrowly scoped and simple installation of the Openshift Container Platform (OCP).  Please refer to the official Red Hat documentation for complete information on the installation procedures.


    * link:https://docs.openshift.com/container-platform/4.3/welcome/index.html[Openshift 4.3 Documentation]

    * link:https://kubernetes.io/docs/home/[Kubernetes]

    * link:https://kubernetes.io/docs/concepts/[Kubernetes Concepts]

Also worth mentioning is the upstream Openshift community project (formally called Origin, now OKD).  There you can find all kinds of additional materials.

    * link://https://www.okd.io/[OKD]

With that said, the steps of preparing and installing OCP in this workshop environment have (currently) been condensed into 2 scripts which execute a set of Ansible Playbooks.  Please follow the steps below to begin your installation of the Openshift Container Platform.

== Preparing for Installation

Please select from one of the following deployment architectures and use the link to complete your installation.

NOTE: you will need sufficient cpu, memory and disk resources for these installations.  Minimum is 16 cores, 64GB memory and 500GB of disk.  

NOTE: all of these deployments are a variant of the User Provided Infrastructure (UPI) installation method.

[discrete]
== Deployment Architectures

  . link:./Install-AIO-Libvirt-Nat.adoc[AOI using Libvirt/KVM Nat]
  . link:./Install-AIO-Libvirt-Bridge.adoc[AOI using Libvirt/KVM Bridge]
  . link:./Install-oVirt.adoc[Deploying with Red Hat Virtualization]
  . *TBD* link:./Install-RHV-Bridge.adoc[Deploying with AWS]
      
[discrete]
== End of Unit

link:../OCP-Workshop.adoc#toc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////

