:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Getting Started

[discrete]
== Additional Reference Materials

NOTE: You are not required to reference outside documentation for these exercises.  This is informational only.

Red Hat's official documentation can be found publicly with the links provided below.  It is important to note that this workshop guide supports a very narrowly scoped and simple installation of the Openshift Container Platform (OCP).  Please refer to the official Red Hat documentation for complete information on the installation procedures.


link:https://access.redhat.com/documentation/en-us/openshift_container_platform/3.9/[Openshift 3.9 Documentation]

link:https://access.redhat.com/documentation/en-us/openshift_container_platform/3.9/html/installation_and_configuration/[Openshift 3.9 Installation and Configuration]

link:https://kubernetes.io/docs/home/[Kubernettes]

link:https://kubernetes.io/docs/concepts/[Kubernettes Concepts]

With that stated, the steps of preparing and installing OCP have been condensed into 3 scripts which call a set of Ansible Playbooks.  Please follow the steps below to begin your installation of the Openshift Container Platform.

== Openshift Pre Installation

=== Sign-On on to your *workstation* session

Using the connection information and credentials provided by the instructor, get yourselves signed into your workstation session.

=== Become the root user

In order to execute the pre-installation steps, we need to become the administrative user 'root'

.[student@workstation ~]$ 
----
sudo -i
----

=== Download the Workshop project from GitHub

.[root@workstation ~]#
----
cd ~
    
git clone https://github.com/xtophd/OCP-Workshop
----

=== Run the pre-install script

NOTE: It is important to be in the correct working directory for these installation procedures to function properly.  

.[root@workstation ~]#
----
cd ~/OCP-Workshop
----

Now you are ready to proceed with executing the pre-install steps.  This typically runs for about 3-5 minutes.    

.[root@workstation OCP-Workshop]#
----
bash 01-pre-install-script.sh
----

While the pre-install script runs, we can breifly review what actions are being performed.  There are 2 primary activities:

* Workstation Actions
** install ansible inventory (/etc/ansible/hosts)
** minimum package installation

* OCP Cluster Node Actions
** reconfigure docker storage to use a block device
** enable and start firewalld
** minimum Package installation

=== Pre-Install Results

NOTE: Please verify that PLAY RECAP reports 0 errors for all hosts.  If you encountered errors, stop here and notify an instructor.

Here is the tail end of a sample output following a successfull run of the pre-install script and ansible playbooks.

.Your output should look like this
[source,indent=4]
----
PLAY RECAP **********
master.example.com         : ok=16   changed=12   unreachable=0    failed=0 // <1>
node1.example.com          : ok=14   changed=11   unreachable=0    failed=0 
node2.example.com          : ok=14   changed=11   unreachable=0    failed=0 
----
<1> All "failed" results should = 0


== Openshift Installation

=== Run the ocp-install script

NOTE: Again, it is important to be in the correct working directory for this to function properly.  This typically runs for about 20-25 minutes.

.[root@workstation OCP-Workshop]#
----
bash 02-ocp-install-script.sh
----

[discrete]
=== A Few Words While the Installer Runs

So you might be asking yourself, *why* another workshop?  What's different about this one?

I have 2 simple goals:

. Explain what the Red Hat Openshift Container Platform is via a hands-on approach
. Deliver an "Ah-Ha" moment for each participant regarding containerized workloads:
** What's in it for operators
** What's in it for developers

So while the OCP installer runs for the next 20 minutes, your presenter may opt to provide a brief presentation.  Valuable topics include _(in the future I hope to provide links to brief documents on the topics below)_:

* "An Introduction to Openshift"
* "Modern Application Development"
* "Architectural Overview of this Workshop"
* or merely host a simple Q&A session

In any case, use this time to set some foundational knowledge.

=== Installation Results

**NOTE** Please verify that PLAY RECAP reports 0 errors for all hosts.  If you encountered errors, stop here and notify an instructor.

Here is the tail end of a sample output following a successfull installation of the Openshift Container Platform.

.Your output should look like this
[source,indent=4]
----
PLAY RECAP **********
localhost                  : ok=13   changed=0    unreachable=0    failed=0  // <1>
master.example.com         : ok=612  changed=260  unreachable=0    failed=0   
node1.example.com          : ok=135  changed=54   unreachable=0    failed=0   
node2.example.com          : ok=135  changed=55   unreachable=0    failed=0   
workstation.example.com    : ok=20   changed=0    unreachable=0    failed=0

INSTALLER STATUS ****************
Initialization             : Complete (0:00:26)
Health Check               : Complete (0:00:28)
etcd Install               : Complete (0:01:08)
NFS Install                : Complete (0:00:17)
Master Install             : Complete (0:03:45)
Master Additional Install  : Complete (0:01:34)
Node Install               : Complete (0:04:33)
Hosted Install             : Complete (0:03:09)
Web Console Install        : Complete (0:00:43)
Service Catalog Install    : Complete (0:03:12)
```
----
<1> All "failed" results should = 0

== Openshift Post Installation

=== Run the post install script

NOTE: Again, it is important to be in the correct working directory for this to function properly.  This typically runs for about 2 minutes.

.[root@workstation OCP-Workshop]#
----
bash 03-post-install-script.sh
----

While the post-install script runs, we can breifly review what actions are being performed.  Again, there are 2 primary activities:

* Workstation Actions
** deploys sample files used by exercises
** configures, enables and starts NFS services
** cleans up yum content

* OCP Cluster Node Actions
** deploys sample files used by exercises
** deletes and deploys OCP router with replicas=2
** cleans up yum content

=== Post Installation Results

Here is the tail end of a sample output following a successfull post-install of the Openshift Container Platform.

.Your output should look like this
[source,indent=4]
----
TASK [CMD cleaning yum content] **************************************************************
[WARNING]: Consider using yum module rather than running yum

changed: [node1.example.com]
changed: [node2.example.com]
changed: [master.example.com]

PLAY RECAP ***********************************************************************************
master.example.com         : ok=10   changed=6    unreachable=0    failed=0   
node1.example.com          : ok=4    changed=1    unreachable=0    failed=0   
node2.example.com          : ok=4    changed=1    unreachable=0    failed=0   
workstation.example.com    : ok=10   changed=6    unreachable=0    failed=0   
----

== Conclusion

The installation of Red Hat Openshift Container Platform is now complete and you should be ready to begin with the exercises.  A couple of remaining words of advice:

1.  Some exercises are dependant on the successful completion of other exericses.  Those dependencies will be noted at the top of each unit.
2.  Pay attention to which linux login to use
3.  Pay attention to which ocp user to use
4.  Also be sure to pay close attention to which host you are executing tasks from

[discrete]
== End of Unit
link:../OCP-Workshop.adoc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////

