:gitrepo: https://github.com/xtophd/OCP-Workshop
:includedir: _includes
:doctype: book
:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= All In One: AIO Libvirt NAT

[discrete]
== Overview

== Preperations

=== Install RHEL @Base



=== Register system

However you get it done, the primary virthost system will need access to additional RHEL repos.  At this time, I'm testing on RHEL 7.7.

    - "rhel-7-server-rpms"
    - "rhel-7-server-optional-rpms"
    - "rhel-7-server-ansible-2.9-rpms"

RHEL 8.1 would probably also work, but not confirmed yet.

    - "rhel-8-for-x86_64-baseos-rpms"
    - "rhel-8-for-x86_64-appstream-rpms"
    - "ansible-2.9-for-rhel-8-x86_64-rpms"
 
=== Install additional packages

NOTE: this process requires and is tested with ansible 2.9

Besides an @Base installation and you will need httpd, git and ansible 2.9.  Once installed, the playbooks will take care of the rest.

----
yum -y install httpd,git,ansible
----

=== Clone the project

----
cd ~

git clone http://github.com/xtophd/OCP4-Workshop
----

=== Copy sample configurations to './config' directory

----
cd ~/OCP4-Workshop/config

copy ../config-samples/libvirt-nat .
----

=== Make Customizations

Any changes you make to the files in './config/' will be left untouched in the event you update the repo.

=== Retrieve RHEL 8.1 DVD

----
mkdir -p /var/www/html/iso/

wget -O /var/www/html/iso/rhel-8.1-x86_64-dvd.iso "<URL>" 
----

=== Retrieve Openshift Pull Secret

Using a browser, go to redhat.com and copy link to the pull-secret

    - https://cloud.redhat.com/openshift/install/metal/user-provisioned

You can either:

    - download the pull-secret.txt and copy it to the virthost system, or
    - "copy" the pull secret and paste it into the file
    
Either way, /root/OCP4-Workshop/config/pull-secret.txt must exist on the virthost before you continue.

== Installation

----
bash setup-libvirt.sh all
----

== Post Installation

----
Coming soon...
----

[discrete]
= The End

.Built-in
asciidoctor-version:: {asciidoctor-version}
safe-mode-name:: {safe-mode-name}

////
Always end files with a blank line to avoid include problems.
////
