:sectnums:
:sectnumlevels: 2
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:toc:

= Understanding Variables and Secrets

*Source Code:* link:https://github.com/xtophd/OCP-Workshop/blob/master/src/bluegreen/index.php[index.php]

== Prepare the Application

Openshift variables are a means to pass key/value pairs from the underlying host to the processess in the container.  Variables can provide configuration data (ie: 

=== Create a Project

.[root@master ~]#
----
oc new-project bluegreen --description="Example with ENV VARs" --display-name="Blue Green"
----

=== Deploy an Image

.[root@master ~]#
----
oc new-app registry.access.redhat.com/rhscl/php-71-rhel7~https://github.com/xtophd/OCP-Workshop --context-dir=/src/bluegreen --name=watcher

oc new-app registry.access.redhat.com/rhscl/php-71-rhel7~https://github.com/xtophd/OCP-Workshop --context-dir=/src/bluegreen --name=worker

oc logs -f bc/worker

oc logs -f bc/watcher
----

=== Expose a Route

.[root@master ~]#
----
oc expose service watcher --hostname=watcher.cloud.example.com

oc expose service worker  --hostname=worker.cloud.example.com
----

== Environment Variables

=== Add Env Vars to Build Configs

.[root@master ~]#
----
oc env dc/worker myMode=worker myColor=blue

curl http://worker.cloud.example.com
----

.[root@master ~]#
----
oc env dc/watcher myMode=watcher myRoute=http://worker.cloud.example.com
----

=== Scale up 'worker' pods

.[root@master ~]#
----

oc scale --replicas=3 dc/worker

oc get pods -o wide
----

With the browser (Firefox) on the workstation, open a tab to http://watcher.cloud.example.com.  The output shown is a single status line from each of pod operating in 'worker' mode.  Continue to monitor this page as you make the changes below.

=== Change Env Vars in Build Configs

.[root@master ~]#
----
oc env dc/worker myColor=green

curl http://worker.cloud.example.com
----

=== Rolling Back Changs

.[root@master ~]#
----
oc rollback dc/worker

curl http://worker.cloud.example.com
----



== Secrets

Secrets decouple sensitive content from the pods that use it.  They can be mounted into containers using a volume plug-in or used by the system to perform actions on behalf of a pod. 

=== Create a Secret

=== Add Secret to Build Configs

=== Consumig Secrets in Pods


== EXTRA STUFF

=== List variables for a POD

oc set env pod/p1 --list

=== Trigger a fresh build after source edit

oc start-build bc/worker
oc logs -f bc/worker

=== emptyDir for image caching volume

=== mysql DB for history/trending

[discrete]
== End of Unit

link:../OCP-Workshop.adoc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
