---

- hosts: localhost
  tasks:

  - block:

        - name: "ocp4_workshop setup: load default vars from xtoph_deploy"
          include_vars:
            name: '{{ item.varname }}'
            file: '{{ item.filename }}'
          when: item.filename|length > 0
          loop:
            - { varname: 'xtoph_default_machine',   filename: '../roles/xtoph_deploy/vars/xtoph-default-machine.yml' }

        - name: "ocp4_workshop setup: deploy configs from templates"
          template:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            owner: root
            group: root
            mode: "{{ item.mode }}"
          with_items:
            - {mode: "0744", src: "master-config.j2",          dest: "{{ t_config_dir}}/config/master-config.yml"}
            - {mode: "0744", src: "credentials.j2",            dest: "{{ t_config_dir}}/config/credentials.yml"}
            - {mode: "0744", src: "xtoph-deploy.j2",           dest: "{{ t_config_dir}}/config/xtoph-deploy.yml"}
            - {mode: "0744", src: "xtoph-deploy-kickstart.j2", dest: "{{ t_config_dir}}/config/xtoph-deploy-kickstart.yml"}
            - {mode: "0744", src: "xtoph-deploy-platform.j2",  dest: "{{ t_config_dir}}/config/xtoph-deploy-platform.yml"}
            - {mode: "0744", src: "xtoph-deploy-resource.j2",  dest: "{{ t_config_dir}}/config/xtoph-deploy-resource.yml"}
            - {mode: "0744", src: "xtoph-ocp4.j2",             dest: "{{ t_config_dir}}/config/xtoph-ocp4.yml"}



    vars:
      - t_config_dir:              "{{ lookup('env','PWD') }}"
      - t_project_name:            "{{ lookup('env','PROJECT_NAME') }}"
      - t_ansible_ip:              "{{ lookup('env','ANSIBLE_IP') }}"
      - t_workshop_user_pw:        "{{ lookup('env','WORKSHOP_USER_PW') }}"
      - t_cluster_name:            "{{ lookup('env','CLUSTER_NAME') }}"
      - t_cluster_wildcard:        "{{ lookup('env','CLUSTER_WILDCARD') }}"
      - t_cluster_provisioner:     "{{ lookup('env','CLUSTER_PROVISIONER') }}"
      - t_cluster_loadbalancer_ip: "{{ lookup('env','CLUSTER_LOADBALANCER_IP') }}"
      - t_cluster_api_ip:          "{{ lookup('env','CLUSTER_API_IP') }}"
      - t_cluster_version:         "{{ lookup('env','CLUSTER_VERSION') }}"
      - t_cluster_strapless:       "{{ lookup('env','CLUSTER_STRAPLESS') }}"
      - t_network_id:              "{{ lookup('env','NETWORK_ID') }}"
      - t_network_gateway:         "{{ lookup('env','NETWORK_GATEWAY') }}"
      - t_network_prefix:          "{{ lookup('env','NETWORK_PREFIX') }}"
      - t_network_netmask:         "{{ lookup('env','NETWORK_NETMASK') }}"
      - t_network_broadcast:       "{{ lookup('env','NETWORK_BROADCAST') }}"
      - t_network_basedomain:      "{{ lookup('env','NETWORK_BASEDOMAIN') }}"
      - t_network_dns_server:      "{{ lookup('env','NETWORK_DNS_SERVER') }}"
      - t_network_time_server:     "{{ lookup('env','NETWORK_TIME_SERVER') }}"
      - t_virthost_type:           "{{ lookup('env','VIRTHOST_TYPE') }}"
      - t_virthost_ip:             "{{ lookup('env','VIRTHOST_IP') }}"
      - t_virthost_uid:            "{{ lookup('env','VIRTHOST_UID') }}"
      - t_virthost_pw:             "{{ lookup('env','VIRTHOST_PW') }}"
      - t_virthost_bmc:            "{{ lookup('env','VIRTHOST_BMC') }}"
      - t_virthost_bmc_uid:        "{{ lookup('env','VIRTHOST_BMC_UID') }}"
      - t_virthost_bmc_pw:         "{{ lookup('env','VIRTHOST_BMC_PW') }}"
      - t_virthost_fqdn:           "{{ lookup('env','VIRTHOST_FQDN') }}"
      - t_virthost_hw:             "{{ lookup('env','VIRTHOST_HW') }}"
      - t_virthost_br_dev:         "{{ lookup('env','VIRTHOST_BR_DEV') }}"
      - t_virthost_br_type:        "{{ lookup('env','VIRTHOST_BR_TYPE') }}"
      - t_virthost_machine:        "{{ lookup('env','VIRTHOST_MACHINE') }}"
      - t_ovirt_manager_ip:        "{{ lookup('env','OVIRT_MANAGER_IP') }}"
      - t_ovirt_manager_fqdn:      "{{ lookup('env','OVIRT_MANAGER_FQDN') }}"
      - t_ovirt_manager_uid:       "{{ lookup('env','OVIRT_MANAGER_UID') }}"
      - t_ovirt_manager_pw:        "{{ lookup('env','OVIRT_MANAGER_PW') }}"
      - t_ovirt_datacenter:        "{{ lookup('env','OVIRT_DATACENTER') }}"
      - t_ovirt_storage_domain:    "{{ lookup('env','OVIRT_STORAGE_DOMAIN') }}"
      - t_ovirt_network_domain:    "{{ lookup('env','OVIRT_NETWORK_DOMAIN') }}"
      - t_ovirt_machine:           "{{ lookup('env','OVIRT_MACHINE') }}"
      - t_addr_bastion:            "{{ lookup('env','ADDR_BASTION') }}"
      - t_addr_bootstrap:          "{{ lookup('env','ADDR_BOOTSTRAP') }}"
      - t_addr_master1:            "{{ lookup('env','ADDR_MASTER1') }}"
      - t_addr_master2:            "{{ lookup('env','ADDR_MASTER2') }}"
      - t_addr_master3:            "{{ lookup('env','ADDR_MASTER3') }}"
      - t_addr_worker1:            "{{ lookup('env','ADDR_WORKER1') }}"
      - t_addr_worker2:            "{{ lookup('env','ADDR_WORKER2') }}"
      - t_addr_sno:                "{{ lookup('env','ADDR_SNO') }}"
      - t_mac_bastion:             "{{ lookup('env','MAC_BASTION') }}"
      - t_mac_bootstrap:           "{{ lookup('env','MAC_BOOTSTRAP') }}"
      - t_mac_master1:             "{{ lookup('env','MAC_MASTER1') }}"
      - t_mac_master2:             "{{ lookup('env','MAC_MASTER2') }}"
      - t_mac_master3:             "{{ lookup('env','MAC_MASTER3') }}"
      - t_mac_worker1:             "{{ lookup('env','MAC_WORKER1') }}"
      - t_mac_worker2:             "{{ lookup('env','MAC_WORKER2') }}"
      - t_mac_sno:                 "{{ lookup('env','MAC_SNO') }}"
      - t_bmc_bastion:             "{{ lookup('env','BMC_BASTION') }}"
      - t_bmc_bootstrap:           "{{ lookup('env','BMC_BOOTSTRAP') }}"
      - t_bmc_master1:             "{{ lookup('env','BMC_MASTER1') }}"
      - t_bmc_master2:             "{{ lookup('env','BMC_MASTER2') }}"
      - t_bmc_master3:             "{{ lookup('env','BMC_MASTER3') }}"
      - t_bmc_worker1:             "{{ lookup('env','BMC_WORKER1') }}"
      - t_bmc_worker2:             "{{ lookup('env','BMC_WORKER2') }}"
      - t_bmc_sno:                 "{{ lookup('env','BMC_SNO') }}"
      - t_bmc_pw_default:          "{{ lookup('env','BMC_PW_DEFAULT') }}"
      - t_bmc_pw_bastion:          "{{ lookup('env','BMC_PW_BASTION') }}"
      - t_bmc_pw_bootstrap:        "{{ lookup('env','BMC_PW_BOOTSTRAP') }}"
      - t_bmc_pw_master1:          "{{ lookup('env','BMC_PW_MASTER1') }}"
      - t_bmc_pw_master2:          "{{ lookup('env','BMC_PW_MASTER2') }}"
      - t_bmc_pw_master3:          "{{ lookup('env','BMC_PW_MASTER3') }}"
      - t_bmc_pw_worker1:          "{{ lookup('env','BMC_PW_WORKER1') }}"
      - t_bmc_pw_worker2:          "{{ lookup('env','BMC_PW_WORKER2') }}"
      - t_bmc_pw_sno:              "{{ lookup('env','BMC_PW_SNO') }}"
      - t_hw_bastion:              "{{ lookup('env','HW_BASTION') }}"
      - t_hw_bootstrap:            "{{ lookup('env','HW_BOOTSTRAP') }}"
      - t_hw_master1:              "{{ lookup('env','HW_MASTER1') }}"
      - t_hw_master2:              "{{ lookup('env','HW_MASTER2') }}"
      - t_hw_master3:              "{{ lookup('env','HW_MASTER3') }}"
      - t_hw_worker1:              "{{ lookup('env','HW_WORKER1') }}"
      - t_hw_worker2:              "{{ lookup('env','HW_WORKER2') }}"
      - t_hw_sno:                  "{{ lookup('env','HW_SNO') }}"
      - t_pw_bastion:              "{{ lookup('env','PW_BASTION') }}"
      - t_pw_bootstrap:            "{{ lookup('env','PW_BOOTSTRAP') }}"
      - t_pw_master1:              "{{ lookup('env','PW_MASTER1') }}"
      - t_pw_master2:              "{{ lookup('env','PW_MASTER2') }}"
      - t_pw_master3:              "{{ lookup('env','PW_MASTER3') }}"
      - t_pw_worker1:              "{{ lookup('env','PW_WORKER1') }}"
      - t_pw_worker2:              "{{ lookup('env','PW_WORKER2') }}"
      - t_pw_sno:                  "{{ lookup('env','PW_SNO') }}"
      - t_uid_bastion:             "{{ lookup('env','UID_BASTION') }}"
      - t_uid_bootstrap:           "{{ lookup('env','UID_BOOTSTRAP') }}"
      - t_uid_master1:             "{{ lookup('env','UID_MASTER1') }}"
      - t_uid_master2:             "{{ lookup('env','UID_MASTER2') }}"
      - t_uid_master3:             "{{ lookup('env','UID_MASTER3') }}"
      - t_uid_worker1:             "{{ lookup('env','UID_WORKER1') }}"
      - t_uid_worker2:             "{{ lookup('env','UID_WORKER2') }}"
      - t_uid_sno:                 "{{ lookup('env','UID_SNO') }}"
      - t_res_bastion:             "{{ lookup('env','RES_BASTION') }}"
      - t_res_bootstrap:           "{{ lookup('env','RES_BOOTSTRAP') }}"
      - t_res_master1:             "{{ lookup('env','RES_MASTER1') }}"
      - t_res_master2:             "{{ lookup('env','RES_MASTER2') }}"
      - t_res_master3:             "{{ lookup('env','RES_MASTER3') }}"
      - t_res_worker1:             "{{ lookup('env','RES_WORKER1') }}"
      - t_res_worker2:             "{{ lookup('env','RES_WORKER2') }}"
      - t_res_sno:                 "{{ lookup('env','RES_SNO') }}"
      - t_name_bastion:            "{{ lookup('env','NAME_BASTION') }}"
      - t_name_bootstrap:          "{{ lookup('env','NAME_BOOTSTRAP') }}"
      - t_name_master1:            "{{ lookup('env','NAME_MASTER1') }}"
      - t_name_master2:            "{{ lookup('env','NAME_MASTER2') }}"
      - t_name_master3:            "{{ lookup('env','NAME_MASTER3') }}"
      - t_name_worker1:            "{{ lookup('env','NAME_WORKER1') }}"
      - t_name_worker2:            "{{ lookup('env','NAME_WORKER2') }}"
      - t_name_sno:                "{{ lookup('env','NAME_SNO') }}"

      - t_blkdev_bastion:          "{{ xtoph_default_machine[t_hw_bastion].kickstart.dev_hints['default']['blkdev']    | default('--REQUIRED--') }}"
      - t_blkdev_bootstrap:        "{{ xtoph_default_machine[t_hw_bootstrap].kickstart.dev_hints['default']['blkdev']  | default('--REQUIRED--') }}"
      - t_blkdev_master1:          "{{ xtoph_default_machine[t_hw_master1].kickstart.dev_hints['default']['blkdev']    | default('--REQUIRED--') }}"
      - t_blkdev_master2:          "{{ xtoph_default_machine[t_hw_master2].kickstart.dev_hints['default']['blkdev']    | default('--REQUIRED--') }}"
      - t_blkdev_master3:          "{{ xtoph_default_machine[t_hw_master3].kickstart.dev_hints['default']['blkdev']    | default('--REQUIRED--') }}"
      - t_blkdev_worker1:          "{{ xtoph_default_machine[t_hw_worker1].kickstart.dev_hints['default']['blkdev']    | default('--REQUIRED--') }}"
      - t_blkdev_worker2:          "{{ xtoph_default_machine[t_hw_worker2].kickstart.dev_hints['default']['blkdev']    | default('--REQUIRED--') }}"
      - t_blkdev_sno:              "{{ xtoph_default_machine[t_hw_sno].kickstart.dev_hints['default']['blkdev']        | default('--REQUIRED--') }}"
      - t_blkdev_ovirt:            "{{ xtoph_default_machine[t_ovirt_machine].kickstart.dev_hints['default']['blkdev'] | default('--REQUIRED--') }}"
      - t_blkdev_virthost:         "{{ xtoph_default_machine[t_virthost_machine].kickstart.dev_hints['default']['blkdev'] | default('--REQUIRED--') }}"

      - t_netdev_bastion:          "{{ xtoph_default_machine[t_hw_bastion].kickstart.dev_hints['default']['netdev']    | default('--REQUIRED--') }}"
      - t_netdev_bootstrap:        "{{ xtoph_default_machine[t_hw_bootstrap].kickstart.dev_hints['default']['netdev']  | default('--REQUIRED--') }}"
      - t_netdev_master1:          "{{ xtoph_default_machine[t_hw_master1].kickstart.dev_hints['default']['netdev']    | default('--REQUIRED--') }}"
      - t_netdev_master2:          "{{ xtoph_default_machine[t_hw_master2].kickstart.dev_hints['default']['netdev']    | default('--REQUIRED--') }}"
      - t_netdev_master3:          "{{ xtoph_default_machine[t_hw_master3].kickstart.dev_hints['default']['netdev']    | default('--REQUIRED--') }}"
      - t_netdev_worker1:          "{{ xtoph_default_machine[t_hw_worker1].kickstart.dev_hints['default']['netdev']    | default('--REQUIRED--') }}"
      - t_netdev_worker2:          "{{ xtoph_default_machine[t_hw_worker2].kickstart.dev_hints['default']['netdev']    | default('--REQUIRED--') }}"
      - t_netdev_sno:              "{{ xtoph_default_machine[t_hw_sno].kickstart.dev_hints['default']['netdev']        | default('--REQUIRED--') }}"
      - t_netdev_ovirt:            "{{ xtoph_default_machine[t_ovirt_machine].kickstart.dev_hints['default']['netdev'] | default('--REQUIRED--') }}"
      - t_netdev_virthost:         "{{ xtoph_default_machine[t_virthost_machine].kickstart.dev_hints['default']['netdev'] | default('--REQUIRED--') }}"

      - t_bootmode_bastion:        "{{ xtoph_default_machine[t_hw_bastion].boot_mode | default('--REQUIRED--') }}"
      - t_bootmode_bootstrap:      "{{ xtoph_default_machine[t_hw_bootstrap].boot_mode | default('--REQUIRED--') }}"
      - t_bootmode_master1:        "{{ xtoph_default_machine[t_hw_master1].boot_mode | default('--REQUIRED--') }}"
      - t_bootmode_master2:        "{{ xtoph_default_machine[t_hw_master2].boot_mode | default('--REQUIRED--') }}"
      - t_bootmode_master3:        "{{ xtoph_default_machine[t_hw_master3].boot_mode | default('--REQUIRED--') }}"
      - t_bootmode_worker1:        "{{ xtoph_default_machine[t_hw_worker1].boot_mode | default('--REQUIRED--') }}"
      - t_bootmode_worker2:        "{{ xtoph_default_machine[t_hw_worker2].boot_mode | default('--REQUIRED--') }}"
      - t_bootmode_sno:            "{{ xtoph_default_machine[t_hw_sno].boot_mode | default('--REQUIRED--') }}"

      - t_usbdelay_bastion:        "{{ xtoph_default_machine[t_hw_bastion].usb_storage_delay | default('0') }}"
      - t_usbdelay_bootstrap:      "{{ xtoph_default_machine[t_hw_bootstrap].usb_storage_delay | default('0') }}"
      - t_usbdelay_master1:        "{{ xtoph_default_machine[t_hw_master1].usb_storage_delay | default('0') }}"
      - t_usbdelay_master2:        "{{ xtoph_default_machine[t_hw_master2].usb_storage_delay | default('0') }}"
      - t_usbdelay_master3:        "{{ xtoph_default_machine[t_hw_master3].usb_storage_delay | default('0') }}"
      - t_usbdelay_worker1:        "{{ xtoph_default_machine[t_hw_worker1].usb_storage_delay | default('0') }}"
      - t_usbdelay_worker2:        "{{ xtoph_default_machine[t_hw_worker2].usb_storage_delay | default('0') }}"
      - t_usbdelay_sno:            "{{ xtoph_default_machine[t_hw_sno].usb_storage_delay | default('0') }}"

      - name: "main.yml : special handling for kickstart netdev"
        set_fact:
          xtoph_deploy: "{{ xtoph_deploy | combine( {'machine_profile': {'kickstart': {'netdev': t_netdev}}}, recursive=True ) }}"
        vars:
          t_netdev:  "{{ xtoph_deploy.machine_profile.kickstart.dev_hints[xtoph_deploy.kickstart_profile.family]['netdev'] | default(xtoph_deploy.machine_profile.kickstart.dev_hints.default.netdev) }}"
        when:
          - xtoph_deploy.kickstart_profile.family is defined
          - xtoph_deploy.machine_profile.kickstart.netdev is defined and xtoph_deploy.machine_profile.kickstart.netdev == ''
          - xtoph_deploy.kickstart_profile.method != 'simple_cdrom'

