:gitrepo: https://github.com/xtophd/RHEL7-Workshop
:docsdir: documentation
:includedir: _include
:doctype: book
:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:imagesdir: ./_include/_images/

NOTE: *ALTHOUGH THIS PROJECT IS FOCUSED ON DELIVERING AN OPENSHIFT WORKSHOP FOR EDUCATIONAL PURPOSES, THE PLAYBOOKS CAN BE USED TO AID INSTALLATION OF OPENSHIFT IN MANY DIFFERENT ENVIRONEMNTS*

= Usage

NOTE:  This "workshop" project and playbooks strive to mimic the hands-on UPI approach to deploying an Openshift cluster.  Shell commands are often used in preference to otherwise fanstastic ansible modules in order to preserve the steps outlined in the actual installation guide.


Default architecture is 7 systems:

  * bastion - utility vm
  * bootstrap - ocp installation provisioner
  * masters-{0,1,2}
  * workers-{0,1}
  
At the completion of the install, the bootstrap node has served it's purpose and can be safely shutdown (or deleted).

== Utility-Host-Only Setup

Deploying Openshift in an automated way typically depends on traditional network services like dhcp-server, dns, http, etc...  One method to deploying OCP is to set up a utility server to run these services.  This simplfies configuration and control of the deployment.

This section describes the steps to configuring the utility server using RHEL 8.

=== Prequisits

  * RHEL 7.7+ or 8.0+
  * installed packages: git, ansible 2.9
  * configured (accessible) repos for base, optional/appstream and ansible
  * log on to cloud.redhat.com and get your pull-secret.txt
  * internet access (either direct or via proxy)

=== RHEL 8 @Base Installation

Starting with a simple deployment of RHEL 8

  * Configure Repos (subscription-manager register)
  * Install ansible-2.9
  * Install git

----
yum install git ansible
----

=== Clone git Repo

As the user 'root', change to you home directory and clone the source.

----
cd ~

git clone http://github.com/xtophd/OCP4-Workshop
----

=== Create Config Files

You can use a sample-config to start this process.  Please note that in this example we are using a "utility-host-only" template.

----
cd ./OCP4-Workshop/config

cp ../sample-configs/utility-host-only/master-config.yml .
----

=== Edit Config Files

WARNING:  You must edit the config files for your deployment.  There is no magic installation.

Just like the name implies 'master-config.yml' is the main configuration file.  Most parameters should be straight forward, but
in particular you need to:

  * fix hostnames, mac addresses & ip addresses
  * set or comment out h_rhcosDEV and r_rhcosNIC accordingly
  
=== Place the Pull Secret

The pull-secret needs to be placed in the config directory.  This is a text file you hopefully downloaded from cloud.redhat.com.

----
cp <PULL_SECRET> ./OCP4-Workshop/config/pull-secret.txt
----

=== Run the Playbooks

Now it's time to run the playbooks which configure and enable the services in preparation for the Openshift cluster deployment.

----
cd ./OCP4-Workshop/
bash prepare-ocp4-workshop.sh all
----

=== Boot the Bootstrap

=== Boot the Masters

=== Boot the Workers

=== Extra Info

Artifacts from the build will be in /root/ocp-<clustername>

Authority files will be in /root/ocp-<clustername>/auth


== LIBVIRT/KVM Host with OCP as VMs (NAT)

If you plan to deploy OCP in a libvirt/kvm based environemnts, you are in luck.  These playbooks can automate everything including the setup of the libvirt/kvm host itself.

Using this configuration, Openshift will be deployed as virtual machines in a NAT'd internal network.  You can easily change this to a bridged network by using alternate playbooks as the template.

NAT is easy because:

  * dhcp, pxe don't conflict with public network
  * it's a real cloud, meaning you get ingress through the haproxy loadbalancer.  The outside world cannot reach your cluter nodes directly.

After setup of the libvirt host is complete, the bastion host is built from DVD and post-configured with ansible plays to enable:

  * dns
  * dhcp
  * pxe
  * matchbox
  * nfs for persistent storage (not supported in PROD, but works for POC)
  * openshift install/ignition generation
  * more...

Lastly, these are default configurations on the virt host but can be changed:

  * vm images will go into /home/virt-images
  * iso images will got into /home/iso
  * network is NAT by default with 192.168.123.xxx and ocp.example.com as internal domain.

Virt host should be loaded with either RHEL 7.7+ or RHEL 8.1+


===  Prerequisites

  * RHEL 7.7+ or 8.0+
  * installed packages: git, ansible 2.9
  * RHEL 8.2 ISO saved in /home/iso
  * configured (accessible) repos for base, optional/appstream and ansible
  * log on to cloud.redhat.com and get your pull-secret.txt
  * internet access (either direct or via proxy)

=== Preperation (libvirt)

On your virt host:

  * subscription manager register and attach host
  * mkdir -p /home/iso
  * mkdir -p /home/virt-images
  * cd /home/iso
  * <PLACE RHEL ISO's HERE>: rhel-8.1-x86_64-dvd.iso rhel-8.2-x86_64-dvd.iso

=== Git Clone Repo

Still on virt host:

  * cd /usr/local/src
  * git clone http://github.com/xtophd/OCP4-Workshop --recurse-submodules

=== Edit the Config Files

WARNING:  You must edit the config files for your deployment.  There is no magic installation.

==== Decide on NAT (prviate) vs. Bridge (public) network configs

  * cd /usr/local/src/OCP4-Workshop/config
  * ln -s ../sample-configs/libvirt-nat/* .
  OR
  * ln -s ../sample-configs/libvirt-bridge/* .


Just like the name implies 'master-config.yml' is the main configuration file.  Most parameters should be straight forward, but
in particular you need to:

  * fix hostnames, mac addresses & ip addresses
  * set or comment out h_rhcosDEV and r_rhcosNIC accordingly
  
=== Place the Pull Secret

  * cd /usr/local/src/OCP4-Workshop/config
  * <PLACE PULL_SECRET HERE>: pull-secret.txt

=== Run the Play Books

Once again, on virt host:

  * cd /usr/local/src/OCP4-Workshop
  * export HTTPPROXY if needed
  * bash prepare-kvm-host.sh all

If all goes well, should just work and about 30 minutes later you have an operational openshift cluster

== MORE COMING SOON...

Master document for this branch can be found here:

* link:{docsdir}/OCP-Workshop.adoc[OCP-Workshop Hands-on Lab]
