:gitrepo: https://github.com/xtophd/RHEL7-Workshop
:docsdir: documentation
:includedir: _includes
:doctype: book
:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:imagesdir: ./_include/_images/

NOTE: *ALTHOUGH THIS PROJECT IS FOCUSED ON DELIVERING AN OPENSHIFT WORKSHOP FOR EDUCATIONAL PURPOSES, THE PLAYBOOKS CAN BE USED TO AID INSTALLATION OF OPENSHIFT IN MANY DIFFERENT ENVIRONMENTS*

= Usage

NOTE:  This "workshop" project and playbooks strive to mimic the hands-on UPI approach to deploying an Openshift cluster.  Shell commands are often used in preference to otherwise fanstastic ansible modules in order to preserve the steps outlined in the actual installation guide.  Also, these playbooks opt to use standard OS services vs. many of the (recently available) prepackaged containerized solutions.  This lends to the backwards compatability and broad customization that is possible with this solution.  At this time, deployments as far back as Openshift 4.2 are still possible using this project.


Default architecture is 7 systems:

  * bastion - utility vm
  * bootstrap - ocp installation provisioner
  * masters-{0,1,2}
  * workers-{0,1}
  
At the completion of the install, the bootstrap node has served it's purpose and can be safely shutdown (or deleted).

== Deployment Guides

Select one of the following deployment guides based on your platform:

  * link:{docsdir}/{includedir}/Install-AIO-Libvirt.adoc[All-in-One using libvirt]
  * link:{docsdir}/{includedir}/Install-oVirt.adoc[oVirt (Red Hat Virtualization)]
  * link:{docsdir}/{includedir}/Install-Utility-Only.adoc[Utility Server Only]


== Workshop Guide and Exercises

Master document for the workshop & exercises be found here:

* link:{docsdir}/OCP-Workshop.adoc[OCP-Workshop Hands-on Lab]
