:gitrepo: https://github.com/xtophd/RHEL7-Workshop
:docsdir: documentation
:includedir: _include
:doctype: book
:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:imagesdir: ./_include/_images/


= DO NOT USE THIS PROJECT YET

NOTE: *THIS PROJECT IS IN ALPHA.  DOCUMENTATION WILL BE UPDATED AFTER BLUEPRINT IS WORKING*

= DO NOT USE THIS PROJECT YET

= Usage

Default architecture is 7 VMs:
  - bastion - utility vm
  - bootstrap - ocp installation provisioner
  - masters-{0,1,2}
  - workers-{0,1}


== Utility-Host-Only Services

Deploying Openshift in an automated way depends on typical services like dhcp-server, dns, http, etc...  One method to deploying OCP is to set up a utility server to run these services.  This simplfies configuration and control of the deployment.

This section describes the steps to configuring the utility server using RHEL 8.

=== RHEL 8 @Base Installation

Starting with a simple deployment of RHEL 8

  - Configure Repos (subscription-manager register)
  - Install ansible-2.9
  - Install git

----
yum install git ansible
----

=== Clone git Repo

As the user 'root', change to you home directory and clone the source.

----
cd ~

git clone http://github.com/xtophd/OCP4-Workshop
----

=== Create Config Files

You can use a sample-config to start this process.  Please note that in this example we are using a NAT example.

----
cd ./OCP4-Workshop/config

cp ../sample-configs/utility-host-only/master-config.yml .
----

Now adjust the parameters for your environment

=== Place the Pull Secret

The pull-secret needs to be placed in the config directory.  This is a text file you hopefully downloaded from cloud.redhat.com.

----
cp <PULL_SECRET> .OCP4-Workshop/pull_secret.txt
----

=== Run the Playbooks

Now it's time to configure and enable the services in preparation for cluster deployment

----
cd ./OCP4-Workshop/
bash prepare-ocp-workshop.sh all
----



== LIBVIRT/KVM Host with OCP as VMs


Systems are deployed in a NAT'd internal network.  You can easily change this to a bridged network.

NAT is easy because:
dhcp, pxe don't conflict with public network
it's a real cloud, ie: you get ingress through the haproxy loadbalancer

The bastion host is built from DVD and post-configured with ansible plays to enable:
dns
dhcp
pxe
matchbox
nfs for persistent storage (not supported in PROD, but works for POC)
openshift install/ignition generation

Lastly, these are default configurations on the virt host but can be changed:

vm images will go into /home/virt-images
iso images will got into /home/iso
network is NAT by default with 192.168.123.xxx and ocp.example.com as internal domain.

Virt host should be loaded with either RHEL 7.7+ or RHEL 8.1+


== Prequisits

  * RHEL 7.7+ or 8.0+
  * installed packages: git, ansible 2.9
  * configured (accessible) repos for base, optional/appstream and ansible
  * log on to cloud.redhat.com and get your pull-secret.txt

== Preperation (libvirt)

On your virt host:

  * subscription manager register and attach host
  * mkdir -p /home/iso
  * mkdir -p /home/virt-images
  * cd /home/iso
  * <PLACE RHEL ISO's HERE>: rhel-8.1-x86_64-dvd.iso rhel-8.2-x86_64-dvd.iso

Still on virt host:

  * cd /usr/local/src
  * git clone http://github.com/xtophd/OCP4-Workshop --recurse-submodules
  * cd /usr/local/src/OCP4-Workshop
  * cd config
  * ln -s ../sample-configs/libvirt-nat/* .
  * <PLACE PULL_SCRET HERE>: pull-secret.txt

Once again, on virt host:

  * cd /usr/local/src/OCP4-Workshop
  * export HTTPPROXY if needed
  * bash prepare-kvm-host.sh all

If all goes well, should just work and about 30 minutes later you have an operational openshift cluster


== Download 

Currently working on the 'wsdeployer' branch.  At this time I am not going to differentiate
a workshop installation without the KVM install/config.  It's all or nothing

----
git clone http://github.com/xtophd/OCP4-Workshop --recurse-submodules -b wsdeployer
----

== Config

Fetch the openshift pull secret from Red Hat
Create your configs.  Here I'm using the 'nat' network configs

----
cd ./OCP4-Workshop/config
cp <PULL_SECRET> ./pull_secret.txt
ln -s ..p/sample-configs/libvirt-nat/* ./OCP4-Workshop/config
----

= MORE COMING SOON...

Master document for this branch can be found here:

* link:{docsdir}/OCP-Workshop.adoc[OCP-Workshop Hands-on Lab]
