:gitrepo: https://github.com/xtophd/OCP4-Workshop
:docsdir: documentation
:includedir: _include
:doctype: book
:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:imagesdir: ./_include/_images/


This document in intended to capture common problems and their mitigations.  Newest additions will be at the top of the document.
At some point, xtoph_deploy problems and mitigations will be moved to the xtoph_deploy repo and simply linked here, but for now it is one document



== (xtoph_deploy) ERROR Host does not support any virtualization options (2021/02/23)

libgcrypt in 8.2 (GA) has a bug that creates a symptom of not being able to deploy a vm into libvirt with virt-install.  Error reports as "Host does not support any virtualization options".

NOTE: resolved by updating libgcrypt with `yum update libgcrypt`



== (xtoph_deploy) Deploying bastion host hangs on iso installation options menu (2021/02/22)

Libvirtd introduced it's own zone into the firwalld ruleset.  The latest xtoph_deploy ansible role has a shell script to detect the existence of the ruleset and will trigger the duplication of the firewall rules for the libvirt zone.

NOTE: resolved by updating to the latest RHEL 8.3 releases with `yum update` AND using the lastest workshop playbooks with `git pull`.



== Bastion builds but other systems do not progress (2021/02/21)

The bastion runs the openshift installer which creates a certificate that is valid for 24 hours.  Simply trying to rerun the deployer after the 24 hour window can have many odd symptoms.

NOTE: To delete all VMs and simply start again, run `xtoph_deploy.sh redeploy`.  

NOTE: To preserve the existing bastion VM and it's current downloads, run `opc4_workshop.sh unlock` followed by `xtoph_deploy.sh deploy`.  This will permit the openshift installer to generate a new certificate without having to download everything anew.
