##
##    !! WARNING !!  Ansible only interprets 'True' and 'False'
##                   as booleans when reading ini files.  Other
##                   values such as 'true' or 'false' would be 
##                   interpreted as strings and would break various
##                   logic tests.  
##
##                   When reading YML files, booleans can take on
##                   many forms and be interpreted correctly.
##
##                   For consistency, only use unquoted booleans: True & False

all: 

  vars:

    ## ----------------------------------------
    ##    Globals that will be phased out

    g_clusterAdmin:       "cloud-admin"
    g_clusterUser:        "cloud-user"


    ## ----------------------------------------
    ##    Workshop Variables

    workshop_vars:

      clustername:          "ocp4ovmix"

      ocp_version:          "4.9"
      ocp_admin_user:       "cloud-admin"
      ocp_user:             "cloud-user"
      ocp_dns_wildcard:     "apps"
      
      network_basedomain:   "example.com"
      network_network:      "192.168.1.0"
      network_netmask:      "255.255.255.0"
      network_broadcast:    "192.168.1.255"
      network_prefix:       "24"
      network_gateway:      "192.168.1.1"
      network_nameserver:   "192.168.1.30"
      network_timeserver:   "192.168.1.60"

      http_proxy:           ""
      https_proxy:          ""

      bastion:

        firewalld:          True
        dns:                True
        dhcp:               True
        dhcp_pxe:           True
        dhcp_uefi_http:     True
        haproxy:            True
        matchbox:           True
        nfs:                True
        ntp:                True
        workshop_user:      True
        workshop_materials: True
        desktop_gui:        False
        desktop_chrome:     False
        desktop_vnc:        False

    workshop_extras:

      network_fqdn:         "{{ workshop_vars.clustername }}.{{ workshop_vars.network_basedomain }}"

      ocp_creds_dir:        "/root/ocp-{{ workshop_vars.clustername }}"
      ocp_wfqdn:            "{{ workshop_vars.ocp_dns_wildcard }}.{{ workshop_vars.clustername }}.{{ workshop_vars.network_basedomain }}"

      nfs_export:           "/home/nfs-{{ workshop_vars.clustername }}"


    ## ----------------------------------------
    ##    Xtoph Deploy Variables

    xtoph_vars:

      deployhost_ip:       "192.168.1.170" 
      clustername:         "{{ workshop_vars.clustername }}"



## ----------------------------------------
## HOSTGROUPS & VARS
## ----------------------------------------



myDeployhost:
  hosts:
    deployer:
      h_pubIP: "{{ xtoph_vars.deployhost_ip }}"
  vars:
    ansible_connection: local



## -----------------



myBastion:
  hosts:
    bastion:
      h_pubIP:         "192.168.1.160"
  vars:
    ansible_host:    "{{ inventory_hostname }}.{{ workshop_extras.network_fqdn }}"
    h_hwPROF:        "ovirt_ocp4custom"
    h_plPROF:        "ovirt"
    h_rsPROF:        "ocp_bastion"
    h_ksPROF:        "rhel84-bootiso"
    h_netDEV:        "ens3"
    h_blkDEV:        "sda"



## -----------------



myBootstrap:
  hosts:
    node1:
      ansible_host:    "{{ inventory_hostname }}.{{ workshop_extras.network_fqdn }}"
      h_pubIP:         "192.168.1.161"

      h_hwPROF:        "ovirt_ocp4custom"
      h_plPROF:        "ovirt"
      h_rsPROF:        "ocp_bootstrap"
      h_ksPROF:        "pxe_nowait"

      h_rhcosDEV:      "sda"
      h_rhcosNIC:      "dhcp"
      h_rhcosUSBdelay: "0"



## -----------------



myMasters:
  hosts:
    node2:
      h_pubIP:       "192.168.1.162" 
    node3:
      h_pubIP:       "192.168.1.163" 
    node4:
      h_pubIP:       "192.168.1.164"

  vars: 
    ansible_host: "{{ inventory_hostname }}.{{ workshop_extras.network_fqdn }}"

    h_hwPROF:        "ovirt_ocp4custom"
    h_plPROF:        "ovirt"
    h_rsPROF:        "ocp_master"
    h_ksPROF:        "pxe_nowait"

    h_rhcosDEV:      "sda"
    h_rhcosNIC:      "dhcp"
    h_rhcosUSBdelay: "0"



## -----------------



myWorkers:
  hosts:
    node5:
      ansible_host:    "{{ inventory_hostname }}.{{ workshop_extras.network_fqdn }}"
      h_pubIP:         "192.168.1.165" 

      h_hwPROF:        "ovirt_ocp4custom"
      h_plPROF:        "ovirt"
      h_rsPROF:        "ocp_worker_odf"
      h_ksPROF:        "pxe_nowait"

      h_rhcosDEV:      "sda"
      h_rhcosNIC:      "dhcp"
      h_rhcosUSBdelay: "0"

    node6:
      ansible_host:    "{{ inventory_hostname }}.{{ workshop_extras.network_fqdn }}"
      h_pubIP:         "192.168.1.166" 

      h_hwPROF:        "ovirt_ocp4custom"
      h_plPROF:        "ovirt"
      h_rsPROF:        "ocp_worker_odf"
      h_ksPROF:        "pxe_nowait"

      h_rhcosDEV:      "sda"
      h_rhcosNIC:      "dhcp"
      h_rhcosUSBdelay: "0"



    node7:
      ansible_host:    "{{ inventory_hostname }}.{{ workshop_extras.network_fqdn }}"
      h_pubIP:         "192.168.1.167" 
      h_pubMAC:        "00:25:90:f0:80:e0"

      h_hwPROF:        "supermicro_x9drd_if"
      h_plPROF:        "baremetal"
      h_rsPROF:        "ocp_worker"
      h_ksPROF:        "pxe_nowait"
      h_pwrOFF:        "False"
      h_rhcosUSBdelay: "0"

      ipmi_fqdn:       "esiso1_bmc.lab.linuxsoup.com"

      h_rhcosDEV:      "sda"

      # Example of Bonded nics with DHCP or with STATIC setups
      #    h_rhcosBOND:     "bond0:enp5s0f1,enp5s0f0:mode=active-backup"
      #
      #    h_rhcosNIC:      "bond0:dhcp"
      #    h_rhcosNIC:      "192.168.1.167::192.168.1.1:255.255.255.0:node7.ocp4ovirt.example.com:bond0:none:192.168.1.160"

      h_rhcosBOND:     "bond0:enp5s0f1,enp5s0f0:mode=active-backup"
      h_rhcosNIC:      "192.168.1.167::192.168.1.1:255.255.255.0:node7.ocp4ovmix.example.com:bond0:none:192.168.1.160"



#myShelter:
#  hosts:
#    bastion:

