debug: true

cleanup: true

hostname: "{{ inventory_hostname }}"

clustername: "{{ xtoph_vars.clustername }}"

selected_profile:
    kickstart: "{{ h_ksPROF | default ('') }}"
    resource:  "{{ h_rsPROF | default ('') }}"
    machine:   "{{ h_hwPROF | default ('') }}"
    platform:  "{{ h_plPROF | default ('') }}"


deployhost:

    ##
    ##     platform_enable: one or more of the following
    ##       - "ovirt"
    ##       - "libvirt"
    ##       - "baremetal"
    ##

    platform_enable: 
     - "ovirt"
     - "baremetal"
    
    ##
    ##    deployhost hostname OR ip that will
    ##    accessible to the deployed VMs
    ##

    ip: "192.168.1.170"

    ##
    ##    firewalld_enable:  ensures firewalld is installed 
    ##                       and enabled on the deployhost
    ##

    firewalld_enable: true

    ##
    ##    dnsmasq_enable:    ensures dnsmasq is installed 
    ##                       and enabled on the deployhost
    ##
    ##    dnsmasq_asprimary: deployed hosts/vms will be
    ##                       configured to use deployhost's
    ##                       dns as primary resolver
    ##                    
    ##                       host/vm resolves to -> 
    ##                         deployhost which forwards to -> 
    ##                           real-dns          
    ##                    

    dnsmasq_enable:  true
    dnsmasq_asprimary:  true

    ##
    ##    http_port:      port to provide kickstart and
    ##                    yum repo services
    ##

    http_enable:  true
    http_port:    "8008"

    ##
    ##    cockpit_enable: install and configure cockpit
    ##
    ##    cockpit_port:   defaults to 9090 if left empty
    ##                    if you change it, the config
    ##                    will ADD the specifed port.
    ##

    cockpit_enable:  false
    cockpit_port:    ""

    ##
    ##    temporary directory for various tasks
    ##
    ##    NOTE: needs to be unique for every host
    ##

    tmp_dir: "/home/tmp/{{ xtoph_vars.clustername }}/{{ inventory_hostname }}"

    ##
    ##    Where with the kickstart configs are stored 
    ##    What is the URL to access the kickstarts
    ##

    kickstart:
        dir: "/var/www/html/ks"
        url: "http://{{ xtoph_vars.deployhost_ip }}:8008/ks"

    ##
    ##    Where will the repos be mounted
    ##    What is the URL to access the repos
    ##

    repos:
        dir: "/var/www/html/repos"
        url: "http://{{ xtoph_vars.deployhost_ip }}:8008/repos"

    ##
    ##    Where are the ISOs stored
    ##

    iso:
        dir: "/home/iso"
    
    ## 
    ##    Enable the creation of the ephemeral dhcp service
    ##

    dhcp: 
        enable:   true
        efi_http: true
        tmp_dir:  "/home/tmp/{{ xtoph_vars.clustername }}/dhcp"

