##
## CUSTOM PLATFORM PROFILES
##


libvirt_nat:

    type:        "libvirt"
    host_fqdn:   "localhost"
    host_ip:     "{{ xtoph_vars.deployhost_ip }}"
    description: "OCP4-Workshop libvirt_nat profile"

    vm:
        name: "{{ xtoph_vars.clustername }}_{{ inventory_hostname }}"
  
    ##
    ##    nested_virt_enable:   add flags to the OS kernel
    ##                          to allow passtrough virt
    ##
 
    nested_virt_enable: true

    kickstart:
        description: "hints to where installers can find devices"
        netdev:  "{{ h_netDEV | default('eno1') }}"
        blkdev:  "{{ h_blkDEV | default('vda') }}"
  
    network:
        default:
  
            description:     "standard libvirt nat network parameters"
            network_name:    "virbr_{{ xtoph_vars.clustername }}"
            undeploy:        true

            fwd_type:        "nat"
            bridge_netdev:   ""
            model:           "virtio"
  
            basedomain:        "{{ workshop_vars.network_basedomain }}"
            network:           "{{ workshop_vars.network_network    }}"
            netmask:           "{{ workshop_vars.network_netmask    }}"
            broadcast:         "{{ workshop_vars.network_broadcast  }}"
            prefix:            "{{ workshop_vars.network_prefix     }}"
            gateway:           "{{ workshop_vars.network_gateway    }}"
            nameserver:        "{{ workshop_vars.network_nameserver }}"
            timeserver:        "{{ workshop_vars.network_timeserver }}"
            fqdn:              "{{ workshop_extras.network_fqdn     }}"
  
    storage:
        default:

            description: "standard libvirt sparse storage parameters"
            qcow_dir: "/home/virt-images"
            bus: "virtio"
            qcow_dir: "/home/virt-images"
            sparse: "true"

