##
## CUSTOM HARDWARE PROFILE 
##   This example creates a new machine entry called 'ovirt_ocs4workshop'
##


ocp4_ovirt_machine:

    description: "Custom oVirt vm with virtio-scsi sparse disks in 2 storage domains"

    platform: "ovirt"

    default_os_type: "rhel_8x64"

    kickstart:
      netdev:  "{{ h_netDEV | default('ens3') }}"
      blkdev:  "{{ h_blkDEV | default('sda') }}"

    storage:
      default:
        note: "Storage bus virtio-scsi, sparse=true"
        bus: "virtio_scsi"
        sparse: "true"
        domain_name: "rhv-data-hiperf"
      ocp_odf:
        description: "Storage for ODF in alternate ovirt data domain"
        bus: "virtio_scsi"
        sparse: "true"
        domain_name: "rhv-data-extra"

    network:
      default:
        note: "Default network entries copied from platform_profile"
