## Authors: 
##   Christoph Doerbeck
##
## Summary:
##   
##

---


##
##      determine if bastion is active,
##      create new inventory named live_bastion



- hosts: myBastion
  gather_facts: no
  tasks:
  - block:

      - name: "ocp4-workshop : bastion-openshift-shutdown : test existence of bastion host"
        delegate_to: localhost
        wait_for:
          host: "{{ ansible_host }}"
          connect_timeout: 5
          port: 22
          sleep: 1
          state: started
          timeout: 10

      - name: "ocp4-workshop : bastion-openshift-shutdown : add active host to hostgroup live_bastion"
        group_by:
          key: "live_bastion"

    rescue:
      - debug: msg="node {{inventory_hostname}} is already down"



##
##      determine if cluster nodes are active,
##      create new inventory named live_nodes
##



- hosts: myBootstrap,myWorkers,myMasters
  gather_facts: no
  tasks:

  - block:

      - name: "ocp4-workshop : bastion-openshift-shutdown : test existence of cluster hosts"
        delegate_to: localhost
        wait_for:
          host: "{{ ansible_host }}"
          connect_timeout: 5
          port: 22
          sleep: 1
          state: started
          timeout: 10

      - name: "ocp4-workshop : bastion-openshift-shutdown : add active cluster hosts to hostgroup live_nodes"
        group_by:
          key: "live_nodes"

    rescue:
      - debug: msg="node {{inventory_hostname}} is already down"



##
##      attempt gracefull shutdown of cluster nodes
##


- hosts: live_bastion
  gather_facts: no
  tasks:



  - name: "ocp4-workshop : bastion-openshift-shutdown : issue gracefull shutdown on live_nodes"
    shell:
      cmd: |
        ssh core@{{ item }} nohup 'sleep 3 && sudo shutdown -h now' &

    with_items: "{{ groups['live_nodes'] }}"


##
##      Try for 3 minutes to wait for graceful shutdown, then exit
##      This allows other tasks to continue (ie: force
##      shutdown via ipmi, ovirt api or libvirt virsh).
##



- hosts: live_nodes
  gather_facts: no
  tasks:

  - name: "common-deploy-post : wait for ssh stopped"
    delegate_to: localhost
    wait_for:
      host: "{{ ansible_host }}"
      connect_timeout: 5
      port: 22
      sleep: 5
      state: stopped
      timeout: 180
    ignore_errors: yes
    when:
      - groups['live_bastion']|length > 0

