## Authors: 
##   Christoph Doerbeck
##
## Summary:
##   This playbook installs and enables a GUI on the bastion node
##

---
- hosts: myBastion
  tasks:

  - name: "ocp4-workshop : bastion-desktop-gui : yum install minimum GUI packages"
    yum: name=gnome-shell,gnome-tweaks,firefox,gnome-terminal state=installed
    register: result

  - name: "ocp4-workshop : bastion-desktop-gui : change to graphical mode"
    shell:
      cmd: |
        systemctl isolate graphical.target
        systemctl set-default graphical.target

