## Authors: 
##   Christoph Doerbeck
##
## Summary:
##   
##

---


##
##      determine if bastion is active,
##      create new inventory named live_bastion



- hosts: myBastion
  gather_facts: no
  tasks:
  - block:

      - name: "ocp4-workshop : bastion-openshift-shutdown : test existence of bastion host via ssh port"
        delegate_to: localhost
        wait_for:
          host: "{{ ansible_host }}"
          connect_timeout: 5
          port: 22
          sleep: 1
          state: started
          timeout: 10

      - name: "ocp4-workshop : bastion-openshift-shutdown : add active host to hostgroup live_bastion"
        group_by:
          key: "live_bastion"

    rescue:
      - debug: msg="node {{inventory_hostname}} is already down"



##
##      determine if workers (and bootstrap) are active,
##      create new inventory named live_workers
##



- hosts: myBootstrap,myWorkers
  gather_facts: no
  tasks:

  - block:

      - name: "ocp4-workshop : bastion-openshift-shutdown : test existence of worker nodes via ssh port"
        delegate_to: localhost
        wait_for:
          host: "{{ ansible_host }}"
          connect_timeout: 5
          port: 22
          sleep: 1
          state: started
          timeout: 10

      - name: "ocp4-workshop : bastion-openshift-shutdown : add active worker nodes hosts to hostgroup live_workers"
        group_by:
          key: "live_workers"

    rescue:
      - debug: msg="node {{inventory_hostname}} is already down"



##
##      determine if masters nodes are active,
##      create new inventory named live_masters
##



- hosts: myMasters
  gather_facts: no
  tasks:

  - block:

      - name: "ocp4-workshop : bastion-openshift-shutdown : test existence of control plane nodes ssh port"
        delegate_to: localhost
        wait_for:
          host: "{{ ansible_host }}"
          connect_timeout: 5
          port: 22
          sleep: 1
          state: started
          timeout: 10

      - name: "ocp4-workshop : bastion-openshift-shutdown : add active cluster hosts to hostgroup live_controlplane"
        group_by:
          key: "live_controlplane"

    rescue:
      - debug: msg="node {{inventory_hostname}} is already down"



##
##      attempt gracefull shutdown of worker nodes
##



- hosts: live_bastion
  gather_facts: no
  tasks:

  - name: "ocp4-workshop : bastion-openshift-shutdown : issue gracefull shutdown on live_workers"
    shell:
      cmd: |
        ssh core@{{ item }} nohup 'sleep 3 && sudo shutdown -h now' &

    with_items: "{{ groups['live_workers'] | default('') }}"



##
##      Try for 3 minutes to wait for graceful shutdown, then exit
##      This allows other tasks to continue (ie: force
##      shutdown via ipmi, ovirt api or libvirt virsh).
##



- hosts: live_workers
  gather_facts: no
  tasks:

  - name: "common-deploy-post : wait for systemd port stopped"
    delegate_to: localhost
    wait_for:
      host: "{{ ansible_host }}"
      connect_timeout: 3
      #port: 4789
      port: 111
      sleep: 5
      state: stopped
      timeout: 180
    ignore_errors: yes
    when:
      - groups['live_bastion']|length > 0



##
##      attempt gracefull shutdown of control plane
##



- hosts: live_bastion
  gather_facts: no
  tasks:

  - name: "ocp4-workshop : bastion-openshift-shutdown : issue gracefull shutdown on live_controlplane"
    shell:
      cmd: |
        ssh core@{{ item }} nohup 'sleep 3 && sudo shutdown -h now' &

    with_items: "{{ groups['live_controlplane'] | default('') }}"



##
##      Try for 3 minutes to wait for graceful shutdown, then exit
##      This allows other tasks to continue (ie: force
##      shutdown via ipmi, ovirt api or libvirt virsh).
##



- hosts: live_controlplane
  gather_facts: no
  tasks:

  - name: "ocp4-workshop : bastion-openshift-shutdown : wait for systemd port stopped"
    delegate_to: localhost
    wait_for:
      host: "{{ ansible_host }}"
      connect_timeout: 3
      port: 111
      sleep: 5
      state: stopped
      timeout: 180
    ignore_errors: yes
    when:
      - groups['live_bastion']|length > 0
