## Authors: 
##   Christoph Doerbeck
##
## Summary:
##   This playbook installs and enables a GUI on the bastion node
##

---
- hosts: myBastion
  tasks:



  ##
  ##    Try loading the credentials.yml file
  ##    if workshopuser_username is not defined
  ##



  - name: "ocp4-workshop : workshop-user : loading credentials"
    include_vars:
      file: "../config/credentials.yml"
    when: workshopuser_username is undefined



  ##
  ##    Only execute these blocked tasks
  ##    if workshopuser_username is defined
  ##

  - block:

      - name: "ocp4-workshop : bastion-vnc : populate service facts"
        service_facts:



      - name: "ocp4-workshop : bastion-vnc : create users .vnc directory"
        file:
          path:  "~{{ workshopuser_username }}/.vnc"
          mode:  "0770"
          owner: "{{ workshopuser_username }}"
          group: "{{ workshopuser_username }}"
          state: directory



      - block:
    
          - name: "ocp4-workshop : bastion-vnc : install vnc packages (RHEL 7)"
            yum: 
              name:
                - tigervnc-server
                - dejavu-sans-mono-fonts
                - dejavu-serif-fonts
                - firefox
                - gnome-classic-session
                - gnome-common
                - gnome-session-xsession
                - gnome-shell
                - gnome-terminal
                - gnome-terminal-nautilus
                - xorg-x11-server-Xorg
                - xorg-x11-fonts-Type1 
              state: installed

          - name: "ocp4-workshop : bastion-vnc : copy systemd config (RHEL 7)"
            copy:
              src:   "/usr/lib/systemd/system/vncserver@.service"
              dest:  "/etc/systemd/system/vncserver@:3.service"
              mode:  "0644"
              owner: "root"
              group: "root"
              remote_src: true

          - name: "ocp4-workshop : bastion-vnc : adjust systemd config (RHEL 7)"
            replace:
              path: '/etc/systemd/system/vncserver@:3.service' 
              regexp: '^(.*)<USER>(.*)$'
              replace: '\1{{ workshopuser_username }}\2'

        when:
          - ansible_distribution == "RedHat"
          - ansible_distribution_major_version == "7"

    
      - block:

          - name: "ocp4-workshop : bastion-vnc : install vnc packages (RHEL 8)"
            yum: 
              name:
                - tigervnc-server
                - dejavu-sans-mono-fonts
                - dejavu-serif-fonts
                - firefox
                - gnome-classic-session
                #- gnome-common
                - gnome-session-xsession
                - gnome-shell
                - gnome-terminal
                - gnome-terminal-nautilus
                - xorg-x11-server-Xorg
                - xorg-x11-fonts-Type1 
              state: installed
    
          - name: "ocp4-workshop : bastion-vnc : adjust vncusers config (RHEL 8)"
            lineinfile:
              dest:   "/etc/tigervnc/vncserver.users"
              line: ":3={{ workshopuser_username }}"
              state:  present

          - name: "ocp4-workshop : bastion-vnc : create vnc service config dir"
            file:
              path:  "/etc/systemd/system/vncserver@:3.service.d"
              mode:  "0755"
              owner: "root"
              group: "root"
              state: directory

          - name: "ocp4-workshop : bastion-vnc : create vnc service override"
            file:
              path:  "/etc/systemd/system/vncserver@:3.service.d/override.conf"
              state: touch
              owner: root
              group: root
              mode:  0644
    
          - name: "ocp4-workshop : bastion-vnc : add 'restart=always' to vnc service override"
            blockinfile:
              dest:  "/etc/systemd/system/vncserver@:3.service.d/override.conf"
              insertbefore: BOF
              block: |
                [Service]
                Restart=always
              state:  present


 
        when:
          - ansible_distribution == "RedHat"
          - ansible_distribution_major_version == "8"



      - name: "ocp4-workshop : bastion-vnc : create users .vnc credentials file"
        file:
          path:  "~{{ workshopuser_username }}/.vnc/passwd"
          mode:  "0600"
          owner: "{{ workshopuser_username }}"
          group: "{{ workshopuser_username }}"
          state: touch



      - name: "ocp4-workshop : bastion-vnc: set .vnc credentials"
        shell:
          cmd: |
            echo '{{ workshopuser_password }}' | vncpasswd -f  > ~/.vnc/passwd
        become: yes
        become_user: "{{ workshopuser_username }}"


    
      ##
      ##    Set SELinux boolean to allow haproxy
      ##    to work on any port
      ##
      
      
      
      - name: "ocp4-workshop : bastion-vnc : test whether SELinux is enabled"
        command: /usr/sbin/selinuxenabled
        ignore_errors: yes
        register: selinux_status
      
      - name: "ocp4-workshop : bastion-vnc : add persistant SELINUX boolean"
        shell: setsebool -P polyinstantiation_enabled 1
        when: selinux_status.rc == 0

      - name: "ocp4-workshop : bastion-vnc : restore SELINUX context on .vnc"
        shell: /sbin/restorecon -vR /home/{{ workshopuser_username }}/.vnc
        when: selinux_status.rc == 0



      - name: "ocp4-workshop : bastion-vnc : enable and restart services"
        service: name="{{ item }}" state=restarted enabled=yes masked=no daemon_reload=yes
        with_items:
          - "vncserver@:3"


    
      - name: "ocp4-workshop : bastion-vnc : add firewalld ports"
        firewalld:
          port: "{{ item }}"
          immediate: yes
          permanent: yes
          state: enabled
        with_items:
          - "5903/tcp"
        when:
          - ansible_facts['services']['firewalld.service']['state'] is defined
          - ansible_facts['services']['firewalld.service']['state'] == 'running'



    when: workshopuser_username is defined


