
---
- hosts: myBastion
  tasks:


  ##
  ##    Try loading the credentials.yml file
  ##    if workshopuser_username is not defined
  ##



  - name: "ocp4-workshop : workshop-user : loading credentials"
    include_vars:
      file: "../config/credentials.yml"
    when: workshopuser_username is undefined



  ##
  ##    Only execute these blocked tasks 
  ##    if workshopuser_username is defined
  ##

  - block:

        - name: "ocp4-workshop-group : workshop-user: create workshopuser-username GID"
          group:
            name: "{{ workshopuser_username }}"
            state: present
      
      
      
        - name: "ocp4-workshop-user : workshop-user: create workshopuser-username UID"
          user:
            name: "{{ workshopuser_username }}"
            password: "{{ workshopuser_password | password_hash('sha512') }}"
            group: "{{ workshopuser_username }}"
            state: present
      
      
      
        - name: "ocp4-workshop-user : workshop-user : add sudo configuration"
          vars:
            t_name: "{{ workshopuser_username }}"
          template:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            owner: root
            group: root
            mode: 0600
          with_items:
            - {src: 'sudoers.j2', dest: '/etc/sudoers.d/ocp4-workshop'}
            - {src: 'sudoers-student.j2', dest: '/etc/sudoers.d/{{ t_name }}'}
      
      
      
        - name: "ocp4-workshop-user : workshop-user : create ~Desktop directory"
          file:
            path:  "~{{ workshopuser_username }}/Desktop"
            mode:  "0755"
            owner: "{{ workshopuser_username }}"
            group: "{{ workshopuser_username }}"
            state: directory
      
      
      
        - name: "ocp4-workshop-user : workshop-user : create friendly openshift console shortcut on desktop (RHEL 7)"
          vars:
            - t_link: "console-openshift-console.{{ workshop_extras.ocp_wfqdn }}"
          template:
            src:   "{{ item.src }}"
            dest:  "~{{ workshopuser_username }}/Desktop/{{ item.dst }}"
            owner: "{{ workshopuser_username }}"
            group: "{{ workshopuser_username }}"
            mode: 0744
          with_items:
            - { src: "workshopuser-console-link-rhel7.j2",  dst: "OCP-Console.desktop" }
            - { src: "workshopuser-terminal-link-rhel7.j2", dst: "Terminal.desktop" }
          when:
            - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
            - ansible_distribution_major_version == "7"
      
      
      
        - name: "ocp4-workshop-user : workshop-user : create friendly openshift console shortcut on desktop (RHEL 8)"
          vars:
            - t_link: "console-openshift-console.{{ workshop_extras.ocp_wfqdn }}"
          template:
            src:   "{{ item.src }}"
            dest:  "~{{ workshopuser_username }}/Desktop/{{ item.dst }}"
            owner: "{{ workshopuser_username }}"
            group: "{{ workshopuser_username }}"
            mode: 0744
          with_items:
            - { src: "workshopuser-console-link-rhel8.j2",  dst: "OCP-Console.desktop" }
            - { src: "workshopuser-terminal-link-rhel8.j2", dst: "Terminal.desktop" }
          when:
            - ansible_distribution == "RedHat"
            - ansible_distribution_major_version == "8"
      
      
        
        - name: "ocp4-workshop-user : workshop-user : create AccountService directory (RHEL 8)"
          file:
            path:  "/var/lib/AccountsService/users/"
            mode:  "0755"
            owner: "root"
            group: "root"
            state: directory
          when:
            - ansible_distribution == "RedHat"
            - ansible_distribution_major_version == "8"
      
        - name: "ocp4-workshop-user : workshop-user : select classic gnome desktop for workshopuser (RHEL 8)"
          template:
            src: "workshopuser-classic-desktop.j2"
            dest: "/var/lib/AccountsService/users/{{ workshopuser_username }}"
            owner: "root"
            group: "root"
            mode: 0644
          when:
            - ansible_distribution == "RedHat"
            - ansible_distribution_major_version == "8"



    when: workshopuser_username is defined





