
---
- hosts: myBastion
  tasks:



  - name: "ocp4-workshop : workshop-materials : determine bastion IP address"
    set_fact:
      f_bastion_ip: "{{ hostvars[item]['h_pubIP'] }}"
    loop: "{{ groups['myBastion'] }}"



  - name: "ocp4-workshop : workshop-materials : install workshop-(scripts) in /usr/local/bin"
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0744
    with_items:
      - {src: 'workshop-approve-csr.j2',                dest: '/usr/local/bin/workshop-approve-csr.sh'}
      - {src: 'workshop-check-health.j2',               dest: '/usr/local/bin/workshop-check-health.sh'}
      - {src: 'workshop-check-dns.j2',                  dest: '/usr/local/bin/workshop-check-dns.sh'}
      - {src: 'workshop-check-operators.j2',            dest: '/usr/local/bin/workshop-check-operators.sh'}
      - {src: 'workshop-check-version.j2',              dest: '/usr/local/bin/workshop-check-version.sh'}
      - {src: 'workshop-config-registry.j2',            dest: '/usr/local/bin/workshop-config-registry.sh'}
      - {src: 'workshop-config-scheduler.j2',           dest: '/usr/local/bin/workshop-config-scheduler.sh'}
      - {src: 'workshop-rsh.j2',                        dest: '/usr/local/bin/workshop-rsh.sh'}
      - {src: 'workshop-validate-service.j2',           dest: '/usr/local/bin/workshop-validate-service.sh'}
      - {src: 'workshop-validate-app.j2',               dest: '/usr/local/bin/workshop-validate-app.sh'}
      - {src: 'workshop-install-helloworld.j2',         dest: '/usr/local/bin/workshop-exercise1-install-helloworld.sh'}
      - {src: 'workshop-kubeadmin.j2',                  dest: '/usr/local/bin/workshop-kubeadmin.sh'}
      - {src: 'workshop-get-console.j2',                dest: '/usr/local/bin/workshop-get-console.sh'}

#      - {src: 'exercise-hello-world.j2',                dest: '/usr/local/bin/exercise-hello-world.sh'}

      - {src: 'exercise1-deploy.j2',                    dest: '/usr/local/bin/exercise1-deploy.sh'}
      - {src: 'exercise1-patch-scc.j2',                 dest: '/usr/local/bin/exercise1-patch-scc.sh'}
      - {src: 'exercise1-install-helloworld.j2',        dest: '/usr/local/bin/exercise1-install-helloworld.sh'}

      - {src: 'exercise2-deploy.j2',                    dest: '/usr/local/bin/exercise2-deploy.sh'}
      - {src: 'exercise2-install-helloworld.j2',        dest: '/usr/local/bin/exercise2-install-helloworld.sh'}

      - {src: 'exercise3-deploy.j2',                    dest: '/usr/local/bin/exercise3-deploy.sh'}
      - {src: 'exercise4-deploy.j2',                    dest: '/usr/local/bin/exercise4-deploy.sh'}
      - {src: 'exercise5-deploy.j2',                    dest: '/usr/local/bin/exercise5-deploy.sh'}

      - {src: 'exercise6-cleanup.j2',                   dest: '/usr/local/bin/exercise6-cleanup.sh'}

      - {src: 'exercise-db-server.j2',                  dest: '/usr/local/bin/exercise-db-server.sh'}



  - name: "ocp4-workshop : workshop-materials : install workshop-(yaml's) in /usr/local/etc"
    vars:
      - p_server: "{{ f_bastion_ip }}"
      - p_path:   "{{ workshop_extras.nfs_export }}"
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0744
    with_items:
      - {src: 'workshop-yaml-identity.j2',      dest: '/usr/local/etc/workshop-identity.yaml'}
      - {src: 'workshop-users-htpasswd.j2',     dest: '/usr/local/etc/workshop-users.htpasswd'}
      - {src: 'exercise-hello-world-pv.j2',     dest: '/usr/local/etc/exercise-hello-world-pv.yaml'}
      - {src: 'exercise-hello-world-pvc.j2',    dest: '/usr/local/etc/exercise-hello-world-pvc.yaml'}
      - {src: 'exercise-hello-world-html.j2',   dest: '/usr/local/etc/exercise-hello-world.html'}
      - {src: 'workshop-yaml-registryPV.j2',    dest: '/usr/local/etc/workshop-registryPV.yaml'}

