## Authors: 
##   Christoph Doerbeck
##
## Summary:
##   
##

---



##
##      determine if workers are active,
##      create new inventory named live_workers
##



- hosts: myWorkers
  gather_facts: no
  tasks:

  - block:

      - name: "ocp4-workshop : bastion-openshift-shutdown : test existence of worker nodes via ssh port"
        delegate_to: localhost
        wait_for:
          host: "{{ ansible_host }}"
          connect_timeout: 5
          port: 22
          sleep: 1
          state: started
          timeout: 10

      - name: "ocp4-workshop : bastion-openshift-shutdown : add active worker nodes hosts to hostgroup live_workers"
        group_by:
          key: "live_workers"

    rescue:
      - debug: msg="node {{inventory_hostname}} is already down"



##
##      determine if masters nodes are active,
##      create new inventory named live_controlplane
##



- hosts: myMasters
  gather_facts: no
  tasks:

  - block:

      - name: "ocp4-workshop : bastion-openshift-shutdown : test existence of control plane nodes ssh port"
        delegate_to: localhost
        wait_for:
          host: "{{ ansible_host }}"
          connect_timeout: 5
          port: 22
          sleep: 1
          state: started
          timeout: 10

      - name: "ocp4-workshop : bastion-openshift-shutdown : add active cluster hosts to hostgroup live_controlplane"
        group_by:
          key: "live_controlplane"

    rescue:
      - debug: msg="node {{inventory_hostname}} is already down"



##
##      attempt gracefull shutdown of worker nodes
##



- hosts: live_workers
  gather_facts: no
  tasks:

  - name: "ocp4-workshop : bastion-openshift-shutdown : issue gracefull shutdown on live_workers"
    shell:
      cmd: |
        ssh core@{{ item }} nohup 'sleep 3 && sudo shutdown -h now' &

    with_items: "{{ groups['live_workers'] | default('') }}"

  - name: "common-deploy-post : wait for systemd port stopped"
    delegate_to: localhost
    wait_for:
      host: "{{ ansible_host }}"
      connect_timeout: 3
      #port: 4789
      port: 111
      sleep: 5
      state: stopped
      timeout: 180
    ignore_errors: yes



##
##      attempt gracefull shutdown of control plane
##



- hosts: live_controlplane
  gather_facts: no
  tasks:

  - name: "ocp4-workshop : bastion-openshift-shutdown : issue gracefull shutdown on live_controlplane"
    shell:
      cmd: |
        ssh core@{{ item }} nohup 'sleep 3 && sudo shutdown -h now' &

    with_items: "{{ groups['live_controlplane'] | default('') }}"

  - name: "ocp4-workshop : bastion-openshift-shutdown : wait for systemd port stopped"
    delegate_to: localhost
    wait_for:
      host: "{{ ansible_host }}"
      connect_timeout: 3
      port: 111
      sleep: 5
      state: stopped
      timeout: 180
    ignore_errors: yes

