## Authors: 
##   Christoph Doerbeck
##
## Summary:
##   This playbook installs and enables a GUI on the bastion node
##

---
- hosts: myBastion
  tasks:

  - name: "ocp4-workshop : bastion-desktop-gui : yum install package group"
    yum:
      name:  '@Workstation'
      state: installed
    register: result
    retries: 10
    until: result is succeeded
    delay: 5

  - name: "ocp4-workshop : bastion-desktop-gui : yum install extra packages"
    yum: name=gnome-tweaks state=installed
    register: result
    retries: 10
    until: result is succeeded
    delay: 5

  - name: "ocp4-workshop : bastion-desktop-gui : user modification"
    user: name="{{ g_studentName }}" groups="wheel"

  - name: "ocp4-workshop : bastion-desktop-gui : change to graphical mode"
    shell:
      cmd: |
        systemctl isolate graphical.target
        systemctl set-default graphical.target

