## Authors:
##   Christoph Doerbeck
##
## Summary:
##   This playbook installs and enables the cockpit webconsole service
##

---
- hosts: myBastion
  tasks:



    - name: "ocp4-workshop : bastion-cockpit : populate service facts"
      service_facts:



    - name: "ocp4-workshop : bastion-cockpit : yum install packages"
      yum: name=cockpit,sos state=installed
      register: result
      retries: 10
      until: result is succeeded
      delay: 5



    - name: "ocp4-workshop : bastion-cockpit : create cockpit systemd drop-in directory"
      file:
        path: "/etc/systemd/system/cockpit.socket.d/"
        mode: "0755"
        owner: "root"
        group: "root"
        state: directory



    - name: "ocp4-workshop : bastion-cockpit : service restart"
      service: name="cockpit.socket" state=restarted enabled=yes daemon-reload=yes



    - name: "ocp4-workshop : bastion-cockpit : firewall configuration"
      firewalld: service="cockpit" permanent=yes immediate=yes state=enabled
      when: 
        - ansible_facts['services']['firewalld.service']['state'] is defined
        - ansible_facts['services']['firewalld.service']['state'] == 'running'



