## Authors: 
##   Christoph Doerbeck
##
## Summary:
##   This playbook installs Google Chrome Browser
##

---
- hosts: myBastion
  tasks:



  - name: "ocp4-workshop : bastion-desktop-chrome : configure yum repositories"
    yum_repository:
      name:        "google-chrome"
      description: "Google Chrome Broswer"
      baseurl:     "http://dl.google.com/linux/chrome/rpm/stable/x86_64"
      enabled:     "yes"
      gpgcheck:    "no"



  - name: "ocp4-workshop : bastion-desktop-chrome : Chrome browser packages installation"
    yum: 
      name:  "google-chrome-stable"
      state: present

