## Authors: 
##   Christoph Doerbeck
##
## Summary:
##   Downloads and unpacks software /root for OCP installation
##

---
- hosts: myBastion

  vars:
    - oc_cmd: "/usr/local/bin/oc"

  tasks:



  ##
  ##    For every node in cluster: 
  ##      until ( node == ready )
  ##       scan for pending CSR's
  ##       approve pending CSR's
  ##       sleep
  ##



  - name: "ocp4-workshop : bastion-openshift-finish : Approve CSR requests until all nodes 'Ready'"
    shell:
      cmd: |
        export KUBECONFIG={{ workshop_extras.ocp_creds_dir }}/auth/kubeconfig
        if [[ `{{ oc_cmd }} get node --no-headers {{ item }}.{{ workshop_extras.network_fqdn }} | awk '{print $2}'` == "Ready" ]] ; then
          exit 0
        else
          for i in `{{ oc_cmd }} get csr | grep -i pending | awk '{print $1}'`; do 
            oc adm certificate approve $i
            sleep 1
          done
          exit 1
        fi 
    register: result
    until:  result.rc == 0
    retries: 600
    delay: 5
    with_items: 
      - "{{ groups['myMasters'] }}"
      - "{{ groups['myWorkers'] }}"



  ##
  ##    Nodes are all ready, scan ssh keys into known hosts
  ##
  ##
  ##    NOTE:  the technique of adding '| true' just ensures
  ##           that regardless of what ssh-keygen finds, the
  ##           result is 'true'.  This should remove the red
  ##           errors we ignore from the output
  ##



  - name: "ocp4-workshop : bastion-openshift-finish : Cleanup ssh keys in knownhosts"
    vars:
      - p_item:      "{{ item }}"
      - p_name:      "{{ hostvars[item]['inventory_hostname_short']}}"
      - p_addr:      "{{ hostvars[item]['h_pubIP'] }}"
      - p_domain:    "{{ workshop_vars.network_basedomain }}"
      - p_cluster:   "{{ workshop_vars.clustername }}"
      - p_fqdn:      "{{ workshop_extras.network_fqdn }}"
    shell:
      cmd: |
        ssh-keygen -R "{{ p_item }}" | true
        ssh-keygen -R "{{ p_name }}" | true
        ssh-keygen -R "{{ p_fqdn }}" | true
        ssh-keygen -R "{{ p_addr }}" | true
    ignore_errors: yes
    loop: "{{ groups['myWorkers'] + groups['myMasters'] + groups['myBootstrap'] }}"



  - name: "ocp4-workshop : bastion-openshift-finish : Add new ssh keys for node"
    vars:
      - p_item:      "{{ item }}"
      - p_name:      "{{ hostvars[item]['inventory_hostname_short']}}"
      - p_addr:      "{{ hostvars[item]['h_pubIP'] }}"
      - p_domain:    "{{ workshop_vars.network_basedomain }}"
      - p_cluster:   "{{ workshop_vars.clustername }}"
      - p_fqdn:      "{{ workshop_extras.network_fqdn }}"
    shell:
      cmd: |
        ssh-keyscan "{{ p_name }}" >> /root/.ssh/known_hosts
        ssh-keyscan "{{ p_fqdn }}" >> /root/.ssh/known_hosts
    ignore_errors: yes
    loop: "{{ groups['myWorkers'] + groups['myMasters'] + groups['myBootstrap'] }}"



  ##
  ##    Now just watch for all clusteroperators ready
  ##    There can be cases when timing is just right, that
  ##    to results of 'get clusteroperators' can show all True.
  ##    But that is harmless.  This cluster is "mostly" ready
  ##    if this exits
  ##



  - name: "ocp4-workshop : bastion-openshift-finish : Watch until all clusteroperators availability is 'True'"
    shell:
      cmd: |
        export KUBECONFIG={{ workshop_extras.ocp_creds_dir }}/auth/kubeconfig
        {{ oc_cmd }} get clusteroperators --no-headers | awk '{print $3}' | grep -i false 
        if [[ $? == 0 ]]; then exit 1; else exit 0; fi
    register: result
    until:  result.rc == 0
    retries: 600
    delay: 5

