## Authors: 
##   Christoph Doerbeck
##
## Summary:
##   This playbook installs and enables a GUI on the bastion node
##

---
- hosts: myBastion
  tasks:



  ##
  ## From Ansible Documentation
  ##    two types of groups. “Package groups” are specified 
  ##    in the rpm itself while “environment groups” are 
  ##    specified in a separate file (usually by the distribution). 
  ##    Unfortunately, this division becomes apparent to ansible 
  ##    users because ansible needs to operate on the group of 
  ##    packages in a single transaction and yum requires groups
  ##    to be specified in different ways when used in that way. 
  ##    Package groups are specified as “@development-tools” and environment groups are “@^gnome-desktop-environment”
  ##



  ##
  ##    RHEL8 is a "Package Group" so we use @
  ##



  - name: "ocp4-workshop : bastion-desktop-gui : Server-with-GUI packages installation (RHEL 8)"
    yum: 
      name:
        - "@Server with GUI"
        - "gnome-tweaks"
      exclude: 
        - "libvirt*"
        - "PackageKit"
        - "gnome-packagekit*"
        - "yelp*"
        - "gnome-boxes"
        - "gnome-software"
        - "anaconda-gui"
        - "initial-setup-gui" 
      state: present
    when:
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "8"



  ##
  ##    RHEL7 is an "Environment Group" so we use @^
  ##



  - name: "ocp4-workshop : bastion-desktop-gui : Server-with-GUI packages installation (RHEL 7)"
    yum: 
      name:
        - "@^Server with GUI"
      exclude: 
        - "libvirt*"
        - "gnome-boxes"
        - "gnome-software"
        - "PackageKit"
        - "gnome-packagekit*"
      state: present
    when:
      - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
      - ansible_distribution_major_version == "7"



  - name: "ocp4-workshop : bastion-desktop-gui : additional common packages installation"
    yum: name=firefox,dejavu-sans-fonts,dejavu-sans-mono-fonts,dejavu-serif-fonts,dejavu-fonts-common state=installed



  - name: "ocp4-workshop : bastion-desktop-gui : change to graphical mode"
    shell:
      cmd: |
        systemctl isolate graphical.target
        systemctl set-default graphical.target

