## Authors: 
##   Christoph Doerbeck
##
## Summary:
##   This playbook installs and enables a GUI on the bastion node
##

---
- hosts: myBastion
  tasks:



  ##
  ##    Try loading the credentials.yml file
  ##    if workshopuser_username is not defined
  ##



  - name: "ocp4-workshop : workshop-user : loading credentials"
    include_vars:
      file: "../config/credentials.yml"
    when: workshopuser_username is undefined



  ##
  ##    Only execute these blocked tasks
  ##    if workshopuser_username is defined
  ##

  - block:

      - name: "ocp4-workshop : bastion-vnc : populate service facts"
        service_facts:



      - name: "ocp4-workshop : bastion-vnc : install vnc packages"
        yum: name=tigervnc-server state=installed



      - name: "ocp4-workshop : bastion-vnc : install additional minimum packages"
        yum: 
          name:
            - dejavu-sans-mono-fonts
            - dejavu-serif-fonts
            - firefox
            - gnome-classic-session
            - gnome-common
            - gnome-session-xsession
            - gnome-shell
            - gnome-shell-extension-common
            - gnome-terminal
            - gnome-terminal-nautilus
            - xorg-x11-server-Xorg
            - xorg-x11-fonts-Type1 
          state: installed



      - name: "ocp4-workshop : bastion-vnc : create users .vnc directory"
        file:
          path:  "~{{ workshopuser_username }}/.vnc"
          mode:  "0770"
          owner: "{{ workshopuser_username }}"
          group: "{{ workshopuser_username }}"
          state: directory



      - block:
    
          - name: "ocp4-workshop : bastion-vnc : copy systemd config (RHEL 7)"
            copy:
              src:   "/usr/lib/systemd/system/vncserver@.service"
              dest:  "/etc/systemd/system/vncserver@:3.service"
              mode:  "0644"
              owner: "root"
              group: "root"
              remote_src: true

          - name: "ocp4-workshop : bastion-vnc : adjust systemd config (RHEL 7)"
            replace:
              path: '/etc/systemd/system/vncserver@:3.service' 
              regexp: '^(.*)<USER>(.*)$'
              replace: '\1{{ workshopuser_username }}\2'

        when:
          - ansible_distribution == "RedHat"
          - ansible_distribution_major_version == "7"

    

    
      - name: "ocp4-workshop : bastion-vnc : adjust vncusers config (RHEL 8)"
        lineinfile:
          dest:   "/etc/tigervnc/vncusers"
          line: ":3={{ workshopuser_username }}"
          state:  present
        when:
          - ansible_distribution == "RedHat"
          - ansible_distribution_major_version == "8"



      - name: "ocp4-workshop : bastion-vnc : create users .vnc credentials file"
        file:
          path:  "~{{ workshopuser_username }}/.vnc/passwd"
          mode:  "0600"
          owner: "{{ workshopuser_username }}"
          group: "{{ workshopuser_username }}"
          state: touch



      - name: "ocp4-workshop : bastion-vnc: set .vnc credentials"
        shell:
          cmd: |
            echo '{{workshopuser_password }}' | vncpasswd -f  > ~/.vnc/passwd
        become: yes
        become_user: "{{ workshopuser_username }}"


    
      - name: "ocp4-workshop : bastion-vnc : enable and restart services"
        service: name="{{ item }}" state=restarted enabled=yes masked=no daemon_reload=yes
        with_items:
          - "vncserver@:3"


    
      - name: "ocp4-workshop : bastion-vnc : add firewalld ports"
        firewalld:
          port: "{{ item }}"
          immediate: yes
          permanent: yes
          state: enabled
        with_items:
          - "5903/tcp"
        when:
          - ansible_facts['services']['firewalld.service']['state'] is defined
          - ansible_facts['services']['firewalld.service']['state'] == 'running'



    when: workshopuser_username is defined


