## Authors: 
##   Christoph Doerbeck
##
## Summary:
##   This playbook intends to do the heavy lifting of configuring the bastion-host based on the paremeters defined in the
##   ansible inventory (config).
##
##   It will install missing packages, pull (wget) openshift installer, rhcos, etc...
##
## Playbook Assumptions:
##     #1 you are executing this on the bastion-host
##     #2 you have configured and copied ssh-keys to itself.  Meaning, ssh root@localhost works without a password
##     #3 you have completed adjustments to ../configs/ocp4poc-default
##

---
- hosts: myBastion
  tasks:

  - name: "BASTION-SETUP: determine if deployment is locked '({{ g_credsDir }}/ocp-workshop-deployment.lock }})"
    stat: path="{{ g_credsDir }}/ocp-workshop-deployment.lock"
    register: deployment_lock
    tags: always

  - set_fact:
      workshop_lock: "{{ deployment_lock.stat.exists }}"
    tags: always

  - debug: var=workshop_lock
    tags: always

- import_playbook: bastion-basics.yml
  tags: basics

- import_playbook: bastion-cockpit.yml
  tags: cockpit

- import_playbook: bastion-desktop-gui.yml
  when: g_useDESKTOP_GUI == "True"
  tags: gui

- import_playbook: bastion-dns.yml
  when: g_useDNS == "True"
  tags: dns

- import_playbook: bastion-matchbox.yml
  when: g_useMATCHBOX == "True"
  tags: matchbox

- import_playbook: bastion-pxe.yml
  when: g_usePXE == "True"
  tags: pxe

- import_playbook: bastion-uefi.yml
  when: g_useUEFI_HTTP == "True"
  tags: uefi

- import_playbook: bastion-dhcp.yml
  when: g_useDHCP == "True"
  tags: dhcp

- import_playbook: bastion-haproxy.yml
  when: g_useHAPROXY == "True"
  tags: haproxy

- import_playbook: bastion-haproxy-vip.yml
  when: g_useHAPROXY_VIP == "True"
  tags: haproxy_vip

- import_playbook: bastion-nfs.yml
  when: g_useNFS == "True"
  tags: nfs

- import_playbook: bastion-httpd.yml
  when: g_useMATCHBOX != "True"
  tags: httpd

##
##    NTP needs to be configured on bastion regardless
##    of g_useNTP.  If g_useNTP is "True" then
##    bastion will be enabled as a source for the 
##    cluster nodes to reference
##

- import_playbook: bastion-ntp.yml
  tags: ntp

## Currently disabled and being developed
#- import_playbook: bastion-squid.yml
#  when: g_useSQUID == "True"
#  tags:
#    - squid

- import_playbook: bastion-tests.yml
  tags: tests

- import_playbook: bastion-openshift.yml
  tags: openshift

- import_playbook: bastion-lock.yml
  tags: lock

- import_playbook: bastion-unlock.yml
  tags: 
    - never
    - unlock

- import_playbook: workshop.yml
  tags: workshop

