##
##    !! WARNING !!  Ansible only interprets 'True' and 'False'
##                   as booleans when reading ini files.  Other
##                   values such as 'true' or 'false' would be 
##                   interpreted as strings and would break various
##                   logic tests.  
##
##                   When reading YML files, booleans can take on
##                   many forms and be interpreted correctly.
##
##                   For consistency, only use unquoted booleans: True & False

all: 

  vars:

    ## ----------------------------------------
    ##    Globals that will be phased out

    g_clusterAdmin:       "cloud-admin"
    g_clusterUser:        "cloud-user"


    ## ----------------------------------------
    ##    Workshop Variables

    workshop_vars:

      clustername:          "$CLUSTER_NAME"

      ocp_version:          "4.11"
      ocp_admin_user:       "cloud-admin"
      ocp_user:             "cloud-user"
      ocp_dns_wildcard:     "$CLUSTER_WILDCARD"
      ocp_vip_cluster:      "$CLUSTER_LOADBALANCER_IP"
      ocp_vip_api:          "$CLUSTER_API_IP"
      ocp_provisioner:      "$CLUSTER_PROVISIONER"

      network_basedomain:   "$NETWORK_BASEDOMAIN"
      network_network:      "$NETWORK_ID"
      network_netmask:      "$NETWORK_NETMASK"
      network_broadcast:    "$NETWORK_BROADCAST"
      network_prefix:       "$NETWORK_PREFIX"
      network_gateway:      "$NETWORK_GATEWAY"
      network_nameserver:   "$NETWORK_DNS_SERVER"
      network_timeserver:   "$NETWORK_TIME_SERVER"

      http_proxy:           ""
      https_proxy:          ""

      bastion:

        assisted_installer: True
        firewalld:          True
        cockpit:            False
        dns:                True
        dhcp:               True
        dhcp_pxe:           True
        dhcp_uefi_http:     True
        haproxy:            True
        matchbox:           True
        nfs:                True
        ntp:                True
        squid:              False
        workshop_user:      True
        workshop_materials: True
        desktop_gui:        False
        desktop_chrome:     False
        desktop_vnc:        False

    workshop_extras:

      network_fqdn:         "{{ workshop_vars.clustername }}.{{ workshop_vars.network_basedomain }}"

      ocp_creds_dir:        "/root/ocp-{{ workshop_vars.clustername }}"
      ocp_wfqdn:            "{{ workshop_vars.ocp_dns_wildcard }}.{{ workshop_vars.clustername }}.{{ workshop_vars.network_basedomain }}"

      nfs_export:           "/home/nfs-{{ workshop_vars.clustername }}"

      squid_http_url:       "http://bastion.{{ workshop_vars.clustername }}.{{ workshop_vars.network_basedomain }}:3128"
      squid_https_url:      ""



    ## ----------------------------------------
    ##    Xtoph Deploy Variables

    xtoph_vars:

      deployhost_ip:       "$ANSIBLE_IP" 
      clustername:         "{{ workshop_vars.clustername }}"
      tmp_dir:             "/home/tmp/{{ workshop_vars.clustername }}/{{ inventory_hostname_short }}"



## ----------------------------------------
## HOSTGROUPS & VARS
## ----------------------------------------

myLibvirtHosts:

  hosts:
    amanda1.lab.linuxsoup.com:
      h_pubIP:       "192.168.1.23"
      h_plPROF:      "custom_kvmhost"

#    amanda2.lab.linuxsoup.com:
#      h_pubIP:       "192.168.1.24"
#      h_plPROF:      "libvirt_custom02"


## -----------------

myDeployhost:
  hosts:
    deployer:
      h_pubIP: "{{ xtoph_vars.deployhost_ip }}"
  vars:
    ansible_connection: local



## -----------------



myBastion:
  hosts:
    bastion:
      h_pubIP: "192.168.1.60"
  vars:
    ansible_host: "{{ inventory_hostname }}.{{ workshop_extras.network_fqdn }}"
    h_hwPROF: "kvm_vda"
    h_plPROF: "custom_kvmhost"
    h_rsPROF: "custom_bastion"
    h_ksPROF: "rhel84-bootiso"
    h_netDEV: "enp1s0"
    h_blkDEV: "vda"



## -----------------



myBootstrap:
  hosts:
    node1:
      h_pubIP:       "192.168.1.61"
  vars: 
    ansible_host: "{{ inventory_hostname }}.{{ workshop_extras.network_fqdn }}"
    h_hwPROF:        "kvm_vda"
    h_plPROF:        "custom_kvmhost"
    h_rsPROF:        "med"
    h_ksPROF:        "custom_kickstart"
    h_rhcosDEV:      "vda"
    h_rhcosNIC:      "dhcp"
    h_rhcosUSBdelay: "0"
    h_rhcosLOADER:   "bios"



## -----------------



myMasters:
  hosts:
    node2:
      h_pubIP:       "192.168.1.62" 
    node3:
      h_pubIP:       "192.168.1.63" 
    node4:
      h_pubIP:       "192.168.1.64"
  vars: 
    ansible_host: "{{ inventory_hostname }}.{{ workshop_extras.network_fqdn }}"
    h_hwPROF:        "kvm_vda"
    h_plPROF:        "custom_kvmhost"
    h_rsPROF:        "custom_master"
    h_ksPROF:        "custom_kickstart"
    h_isoURL:        "http://192.168.1.60:8008/assets/{{ workshop_vars.clustername }}.iso"
    h_rhcosDEV:      "vda"
    h_rhcosNIC:      "dhcp"
    h_rhcosUSBdelay: "0"
    h_rhcosLOADER:   "bios"



## -----------------



myWorkers:
  hosts:
    node5:
      h_pubIP:       "192.168.1.65" 
    node6:
      h_pubIP:       "192.168.1.66" 
  vars: 
    ansible_host: "{{ inventory_hostname }}.{{ workshop_extras.network_fqdn }}"
    h_hwPROF:        "kvm_vda"
    h_plPROF:        "custom_kvmhost"
    h_rsPROF:        "custom_worker"
    h_ksPROF:        "custom_kickstart"
    h_isoURL:        "http://192.168.1.60:8008/assets/{{ workshop_vars.clustername }}.iso"
    h_rhcosDEV:      "vda"
    h_rhcosNIC:      "dhcp"
    h_rhcosUSBdelay: "0"
    h_rhcosLOADER:   "bios"

