= 11. Hello World(s) via WebUI

== 11.1 Sign-on as admin

Use Firefox to Sign-On as use admin

https://master.example.com:8443

Select Advanced button

Scroll Down

Select Add Exception button

Select Confirm Security Exception

Proceed to Sign-On as user admin with the password set during the Users and Roles unit.

== 11.1 Create a Project

Go To Front Landing Page

Select **Create Project** *{Top Right}*
Name: webui-hello1
Display Name: WebUI Hello 1
Description: *{leave blank}*

== 11.2 Create an Application from a Container Image

Using the Search bar, search for **httpd** and select the *QUICKSTART HTTPD*

Select **Next>**

Add to Project: WebUI Hello World

Use the defaults for all values unless specified below:

Name: webui-hello1

Git Repository URL: https://github.com/xtophd/OCP-Workshop

Context Directory: /src/helloworld

Application Hostname: webui-hello1.cloud.example.com

Select **Create**

You just instructed openship to create a new application called **webui-hello**:
  - The container was deployed to a node and brought online.

Now let's have a closer inspection.  

Click "Continue to Project Overview"

=== Inspect the Deployments

=== Inspect the Pods

=== Inspect the Services

=== Inpects the Routes

=== Validate the Application

Create and use a new Tab in Firefox to view your new application.  The link should be http://webui-hello1.cloud.example.com





```
: [root@master ~]#

oc status
    
oc get pods
    
oc get services
```

The IP address shown for the service is the internal non-routable network for the pod.  From any node in the cluster, we can test the pod for application functionality before exposing the service to the public. 

```
: [root@master ~]#

curl -Is http://{ip_address}}:8080
```

== 11.3 Add a Route

Routers are the processes responsible for making services accessible to the outside world, so the routers must be reachable. Routers run as containers on nodes - therefore, the nodes where routers run must be reachable themselves.


== 11.4 Validate Application



== Conclusion

= End of Unit

link:https://github.com/xtophd/OCP-Workshop/tree/master/documentation[Return to Index]
