:gitrepo: https://github.com/xtophd/OCP-Workshop
:includedir: _includes
:doctype: book
:sectnums:
:sectnumlevels: 3

= Openshift Container Platform Hands-On Workshop

[discrete]
== Presented By

  * Christoph Doerbeck 
  * William Caban Babilonia

[discrete]
== Introduction

This guide is intended to support a series of workshop exercises for individuals getting familiar with Red Hat's Openshift  Container Platform.

This is not an official Red Hat sponsored effort although I am currently employeed by Red Hat.  Rather this is a tool I use to teach myself and those I interact with professionally about new and emerging technologies.

In the spirit of Opensource, I am attempting to make my work publicly accessible for reuse by others.  Please be patient as I navigate my way through managing a day job while building out this project (workshop).

NOTE:  This whole effort is done using official Red Hat software and although things can be set up to work with upstream software components (CentOS, Origin, etc...) I currently do not have the bandwidth to support the development and testing of alternate build environments.

[discrete]
== Conventions Used

[discrete]
=== Tips, Notes & Warnings

TIP: Extra info which could be helpful, but not essential for a given task or discussion

NOTE: Special information to pay attention

WARNING: Critical information which could help you avoid major set backs

[discrete]
=== Executing tasks on the CLI

[discrete]
==== Input

Each block of commands to execute will be labeled with the expected *user-id* and *host*.  To enhance cut & paste efficiency, the command prompt is omitted from each line.

.[root@master ~]#
----
systemctl status sshd
----

[discrete]
==== Output

Sample output will be titled with _'Your output should look like this'_ (or _'Command Output'_) and also be indented to help with visual identification.  Sometimes there will also be footnotes and/or callouts.

.Command Output
[source,indent=4]
----
● sshd.service - OpenSSH server daemon
   Loaded: loaded (/usr/lib/systemd/system/sshd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-02-26 12:04:16 EST; 27min ago // <1>
     Docs: man:sshd(8)
           man:sshd_config(5)
 Main PID: 3094 (sshd)
   CGroup: /system.slice/sshd.service
           └─3094 /usr/sbin/sshd -D
...<snip>...
----
<1> This is the line we are interested in with a special note

[discrete]
==== Alternate Commands

The workshop often provides cheat-scripts to ease certain complex tasks.  This helps the class stay focused and reduces the likelihood of errors and disruptions to the workshop delivery.  Honestly, we are not here to learn `vi`, `emacs` or start debates about the merits of `sed` and `awk`.

The native commands which the cheat-scripts utilize will be documented in the following way.

.[root@master ~]#
----
cheat-service-status.sh
----

[NOTE]
====
_Native command(s) to verify system service_
----
systemctl status sshd
----
====


[discrete]
== How to Connect

There are three options to complete the lab.

  . Follow the instructions to download the ssh-key and use a local terminal for the majority of exercises
  . Skip downloading the ssh-key and simply use a local terminal with credentials provided by your instructors
  . The last bullet of the LAB INFORMATION page, provides a link 'to consoles'.  By clicking that link, you can get true console access to "0WORKSTATION".  

NOTE: you will need true console (GUI) on "0WORKSTATION" for the *Wayland* and *Web Console* units.

[discrete]
== Openshift Container Platform: EXERCISES

[#toc]
  . link:{includedir}/Getting-Started.adoc[*Workshop Preparation* - DO THIS FIRST! ] _(workstation)_
  
  . link:{includedir}/Docker-Fundamentals.adoc[Docker Fundamentals]
  . link:{includedir}/CLI-First-Time-Login.adoc[CLI - First Time Login]
  . link:{includedir}/CLI-Hello-World.adoc[CLI - Hello World]
  . link:{includedir}/WebUI-First-Time-Login.adoc[WebUI - First Time Login]
  . link:{includedir}/WebUI-Hello-World.adoc[WebUI - Hello World]
  . link:{includedir}/CLI-BlueGreen-Deployments.adoc[CLI - Blue+Green Deployments]

////  
TO PRINT THIS DOC REMOVE THIS LINE AND COMMENTS AROUND INCLUDES
include::{includedir}/Docker-Fundamentals.adoc[leveloffset=+1]
include::{includedir}/CLI-First-Time-Login.adoc[leveloffset=+1]
include::{includedir}/CLI-Hello-World.adoc[leveloffset=+1]
include::{includedir}/WebUI-First-Time-Login.adoc[leveloffset=+1]
include::{includedir}/WebUI-Hello-World.adoc[leveloffset=+1]
include::{includedir}/CLI-BlueGreen-Deployments.adoc[leveloffset=+1]
////

[discrete]
= The End

.Built-in
asciidoctor-version:: {asciidoctor-version}
safe-mode-name:: {safe-mode-name}

////
Always end files with a blank line to avoid include problems.
////
