:sectnums:
:sectnumlevels: 3
:source-indent: 4

= CLI Hello World

A "Hello, World!" program is traditionally used to illustrate the basic syntax of a programming language.  The program merely outputs or displays "Hello, World!" to a user. Due to it's simplicity in nature, it is often the very first program people write when learning a new language or platform.

This exercise will step through everything needed to bring a "Hello, World!" program online in our Openshift Container Platform.  In fact, we are going to do it several different ways to illustrate some best and worst practices of container usage.

There are 4 fundamental steps to deploying an application in the Openshift Container Platform:

  . **oc login** - sign-on with proper credentials
  . **oc new project** - create a project
  . **oc new-app** - create an application
  . **oc expose** - expose the service

== My First Application

=== Sign-on as admin

In the Unit "Users and Roles", you created an admin user which we will utilize for this exercise.  If you did not perfrom this, hop to that section right now and complete that task before moving on.

Connect to the master and sign-in as user *admin*.

.[root@workstation ~]#
----
ssh master.example.com
----

Now sign-on to Openshift with the `admin` credential you created earlier

.[root@master ~]#
----
oc login -u admin
----

Ensure that you are using the *default* project

.[root@master ~]#
----
oc project default
----

=== Create a Project

The *project* is openshift's ... yada yada ...  Users, roles, applications, services, routes, et al... are all tied together in a **project** definition.  

.[root@master ~]#
----
oc new-project helloworld --description="My First OCP App" --display-name="Hello World"
----


.[root@master ~]#
----
oc get projects
----

.Your output should look like this
[source,indent=4]
----
NAME                                DISPLAY NAME   STATUS
default                                            Active
helloworld                          Hello World    Active
kube-public                                        Active
kube-service-catalog                               Active
kube-system                                        Active
logging                                            Active
management-infra                                   Active
openshift                                          Active
openshift-ansible-service-broker                   Active
openshift-infra                                    Active
openshift-node                                     Active
openshift-template-service-broker                  Active
openshift-web-console                              Active
----

.[root@master ~]#
----    
oc describe project helloworld
----  

.Your output should look like this
[source,indent=4]
----
Name:                   helloworld
Created:                8 seconds ago
Labels:                 <none>
Annotations:            openshift.io/description=My First OCP App
                        openshift.io/display-name=Hello World
                        openshift.io/requester=admin
                        openshift.io/sa.scc.mcs=s0:c11,c5
                        openshift.io/sa.scc.supplemental-groups=1000120000/10000
                        openshift.io/sa.scc.uid-range=1000120000/10000
Display Name:           Hello World
Description:            My First OCP App
Status:                 Active
Node Selector:          <none>
Quota:                  <none>
Resource limits:        <none>
----

=== Create an Application from a Container Image

We are not quite ready to start building our own container images, so we will leverage an existing one available from the RedHat's Container Registry.

.[root@master ~]#
----
oc new-app registry.access.redhat.com/rhscl/httpd-24-rhel7 --name=hello-app
----

You just instructed Openshift to create a new application called **hello-app**.  Without getting caught up in the details, basically what happens is:

  * Openshift checks the local catalog for an existing copy of the specified image **httpd-24-rhel7**
  * Since this is our first deployment in Openshift, the image was likely not available and so Openshift automatically fetches it from the Red Hat Container Registry and adds it to the local catalog
  * A **build container** is initiated to contruct the desired image (ie: customizations or source integration)
  * A **deployment container** is initiated to launch the desired image
  * and *Voi La!!!* The container is deployed and ready to go to work.

Now let's have a closer inspection.

.[root@master ~]#
----
oc status
    
oc get pods
    
oc get services
----

The IP address shown for the service is the internal non-routable network for the pod.  From any node in the cluster, we can test the pod for application functionality before exposing the service to the public. 

.[root@master ~]#
----
curl http://{ip_address}}:8080
----

=== Add a Route

*Be sure that you succesfully deployed a new router with sufficient replicas to have one on each node.  Dnsmasq does not support round-robin on a wildcard entry.  I am also exploring using nodeSelector to have the router run on the master*

Routers are the processes responsible for making services accessible to the outside world, so the routers must be reachable. Routers run as containers on nodes - therefore, the nodes where routers run must be reachable themselves.

.[root@master ~]#
----
oc expose service hello-app --hostname=helloworld.cloud.example.com
----

We can also monitor the deployment of the application by running the following command.  This command will exit once the deployment has completed and the web application is ready.

.[root@master ~]#
----
oc rollout status dc/hello-app

oc get routes
----

=== Validate Application

.[root@master ~]#
----
curl http://helloworld.cloud.example.com
----

=== Exploring the Container

Now we will take a moment to poke around the container namespace.  We need the pods full name in order to connect to a shell within the container.

.[root@master ~]#
----
oc get pods

oc rsh {{ POD NAME }}
----

Now that you have connected to the active container, have a look around


.sh-4.2$
----
id
----

.Your output should look like this
[source,indent=4]
----
uid=1000120000 gid=0(root) groups=0(root),1000120000
----

.sh-4.2$
----
ps -ef
----
    
.Your output should look like this
[source,indent=4]
----
UID         PID   PPID  C STIME TTY          TIME CMD
default       1      0  0 14:26 ?        00:00:03 httpd -D FOREGROUND
default      24      1  0 14:26 ?        00:00:00 /usr/bin/cat
default      25      1  0 14:26 ?        00:00:00 /usr/bin/cat
default      26      1  0 14:26 ?        00:00:00 /usr/bin/cat
default      27      1  0 14:26 ?        00:00:00 /usr/bin/cat
default      28      1  0 14:26 ?        00:00:18 httpd -D FOREGROUND
default      29      1  0 14:26 ?        00:00:18 httpd -D FOREGROUND
default      31      1  0 14:26 ?        00:00:18 httpd -D FOREGROUND
default      35      1  0 14:26 ?        00:00:18 httpd -D FOREGROUND
default      37      1  0 14:26 ?        00:00:18 httpd -D FOREGROUND
default      74      0  0 17:50 ?        00:00:00 /bin/sh
default      84     74  0 17:50 ?        00:00:00 ps -ef
----

Normally files serverd by httpd go into /var/www/html, but the security-conscious random uid does not have permissions to write to this directory (or any other directory than the tmp dirs).

.sh-4.2$
----
cd /var/www/
    
ls -la
----

.Your output should look like this
[source,indent=4]
----
total 0
drwxr-xr-x.  4 default root  33 Jul 17 17:12 .
drwxr-xr-x. 19 root    root 249 Jul 17 17:13 ..
drwxr-xr-x.  2 default root   6 May  9 13:18 cgi-bin
drwxr-xr-x.  2 default root   6 May  9 13:18 html
----


The primary thing we are trying to point out here is that the UID the process is running with (ie: **1000120000**) does not have permissions to write to any part of the container filesystem except traditionally open directories like **/tmp** or **/var/tmp**.  Next, you will do a series of exercises detailing how to make adjustments to the project and deploy a real helloworld application.

When you are done exploring the container namespace, exit the shell and return to command-line of master.example.com


.sh-4.2$
----
exit
----

== Making an authentic "Hello, World!"

=== Solution #1 - Change Security Attributes

For our first solution, we are going to adjust the current project's security attribute to enable some minor modifications to a deployed pod.  We begin by editing the *namespace attributes* of the *helloworld* project.
    
.[root@master ~]#
----
oc edit namespace helloworld
----

.Adjust the following parameter
----
openshift.io/sa.scc.uid-range: 1001/10000
----

Now we will use 'oc rollout' to deploy a fresh instance of our hello-app pod.
    
.[root@master ~]#
----
oc rollout latest dc/hello-app

oc get pods
----

Depending on how quickly you run *oc get pods* after rolling out the new deployment, you may see the ContainerCreating container running and/or the pre-existing deployment of *hello-app-1-????* Terminating.
Never the less, after rolling out the new pod kubenettes will (by default) shutoff and remove older 
versions of the pod.

.Your output should look like this
[source,indent=4]
----
NAME                READY     STATUS        RESTARTS   AGE                                   
hello-app-1-wbq42   0/1       Terminating   0          2h                                    
hello-app-2-lhvgp   1/1       Running       0          10s
----



.[root@master ~]#
----
oc get pods
    
oc rsh {{ POD NAME }}
----

Now that you are back in the container namespace, have a look at the /var/www/html directory and see if you notice something different.

.sh-4.2$
----
id
----

.Your output should look like this
[source,indent=4]
----
uid=1001(default) gid=0(root) groups=0(root),1000120000
----

.sh-4.2$
----
cd /var/www
ls -la
----

.Your output should look like this
[source,indent=4]
----
total 0
drwxr-xr-x.  4 default root  33 Jul 17 17:12 .
drwxr-xr-x. 19 root    root 249 Jul 17 17:13 ..
drwxr-xr-x.  2 default root   6 May  9 13:18 cgi-bin
drwxr-xr-x.  2 default root   6 May  9 13:18 html
----

.sh-4.2$
----
exit
----

To save time and avoid the complexity of editing an HTML file, we will just copy an exist file into the running container.

.[root@master ~]#
----
oc get pods

oc cp /var/tmp/helloworld.html {{ POD NAME }}:/var/www/html/index.html
    
curl http://helloworld.cloud.example.com
----

.Your output should look like this
[source,indent=4]
----
<html>
<body>
Hello, World!
</body>
</html>
----

IMPORTANT: The solution you just completed is NOT a recommended solution on how to deploy a container for production use.  This solution was provided to touch on a few concepts unique to the Openshift Container Platform: container design, project attributes, process uid/gid (ie: namespaces) in a containerized environment, etc...

=== Solution #2 - Use emptyDir

.[root@master ~]#
----
oc new-project helloworld2 --description="My Second OCP App" --display-name="Hello World II"
    
oc new-app registry.access.redhat.com/rhscl/httpd-24-rhel7 --name=hello-app2
    
oc set volume dc/hello-app2 --add --mount-path /var/www/html --type emptyDir
    
oc expose service hello-app2 --hostname=helloworld2.cloud.example.com
    
oc rollout status dc/hello-app2
----

NOTE: You will need to wait until the pod is finished being deployed until you can inject a custom HTML file into the container image.

.Your output should look like this
[source,indent=4]
----
Waiting for rollout to finish: 0 of 1 updated replicas are available...                      
Waiting for latest deployment config spec to be observed by the controller loop...           
replication controller "hello-app2-2" successfully rolled out 
----

Now you can proceed with customizing the deployed (and live) pod.

.[root@master ~]#
----
oc get pods

oc cp /var/tmp/helloworld.html {{ POD NAME }}:/var/www/html/index.html
    
curl http://helloworld2.cloud.example.com
----

.Your output should look like this
[source,indent=4]
----
<html>
<body>
Hello, World!
</body>
</html>
----

If you happen to rsh into the container namespace, have a look at the permissions of /var/www/html.  You will notice that it matches the process uid.

Although it is not considered a best practice to inject files into a container during runtime, this method has it's niche applications.  What is important to note is the any filesystems mounted with emptyDir and non-persistant and will be destoyed when the container is stoppped.

=== Solution #3 - Use NFS

The purpose of this unit is not to boil the ocean with "Hello, World!".  Rather we are trying to provide basic principals of how a container functions.  So with that in mind, our next solution will be to utilize some network storage (ie: NFS) to provide the common source for our helloworld web server.

During the pre-installation phase of this lab, the host workshop.example.com was configured with an NFS server and an export called /exports/helloworld.  Let's simply mount that within the container to demonstrate our "Hello, World!" again.

.[root@master ~]#
----
oc new-project helloworld3 --description="My Third OCP App" --display-name="Hello World III"
    
oc create -f /var/tmp/helloworld-pv.yml
----

.Your output should look like this
[source,indent=4]
----
persistentvolume "helloworld-pv" created
----

.[root@master ~]#
----
oc get pv
----

.Your output should look like this
[source,indent=4]
----
NAME            CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM     STORAGECLASS   REASON    AGE
helloworld-pv   5Gi        RWO            Recycle          Available                                      7s
----

Now create the persistent volume claim. 

.[root@master ~]#
----
oc create -f /var/tmp/helloworld-pv-claim.yml
----

.Your output should look like this
[source,indent=4]
----
persistentvolumeclaim "helloworld-claim" created
----

Next check the status of the pv and pvc.  You should see that the STATUS of the pv has changed to *Bound* and the CLAIM is held by *helloworld3/helloworld-claim*.  Likewise, the pvc will show a STATUS of *Bound* to the VOLUME *helloworld-pv*

.[root@master ~]#
----
oc get pv

oc get pvc
----

.Your output should look like this
[source,indent=4]
----
NAME            CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                          STORAGECLASS   REASON    AGE
helloworld-pv   5Gi        RWO            Recycle          Bound     helloworld3/helloworld-claim

NAME               STATUS    VOLUME          CAPACITY   ACCESS MODES   STORAGECLASS   AGE
helloworld-claim   Bound     helloworld-pv   5Gi        RWO                           4s
----

Now that the storage prep-work is complete, we can proceed: 

  * create the pod, 
  * assign the storage 
  * expose the route.

.[root@master ~]#
----
oc new-app registry.access.redhat.com/rhscl/httpd-24-rhel7 --name=hello-app3

oc set volume dc/hello-app3 --add --mount-path /var/www/html --type persistentVolumeClaim --claim-name=helloworld-claim

oc expose service hello-app3 --hostname=helloworld3.cloud.example.com

oc get pods

curl http://helloworld3.cloud.example.com
----

.Your output should look like this
[source,indent=4]
----
<html>
<body>
Hello, World!
</body>
</html>
----

=== Solution #4 - Use Source Control (git)

Next we will implement the ideal solution.  Using a source code repository we will initiate a container deployment which will pull the source code and layer it into a base container (ie: source to images / S2I) and deploy it as a single unified image.

.[root@master ~]#
----
oc new-project helloworld4 --description="My Fourth OCP App" --display-name="Hello World IV"   
     
oc new-app registry.access.redhat.com/rhscl/httpd-24-rhel7~https://github.com/xtophd/OCP-Workshop --context-dir=/src/helloworld --name=hello-app4
    
oc logs -f bc/hello-app4
    
oc get builds
    
oc get pods
    
oc get events
    
oc rollout status dc/hello-app4
    
oc expose service hello-app4 --hostname=helloworld4.cloud.example.com
    
curl http://helloworld4.cloud.example.com
----

=== Solution #5 - Use Dockerfile

Next we will implement another solution using a Dockerfile.  Again, using a source code repository we we initiate a container deployment but this time we only specify a source with a `Dockerfile`.

.[root@master ~]#
----
oc new-project helloworld5 --description="My Fifth OCP App" --display-name="Hello World V"   
     
oc new-app https://github.com/xtophd/OCP-Workshop --context-dir=/src/dockerfile --name=hello-app5
    
oc logs -f bc/hello-app4
    
oc get builds
    
oc get pods
    
oc get events
    
oc rollout status dc/hello-app5
    
oc expose service hello-app5 --hostname=helloworld5.cloud.example.com
    
curl http://helloworld5.cloud.example.com
----

== Clean Up (Optional)

.[root@master ~]#
----
oc get pods --all-namespaces -o wide
----

Now it is time to clean everything up.

.[root@master ~]#
----
oc project default
    
oc delete project helloworld
    
oc delete project helloworld2
    
oc delete project helloworld3
    
oc delete project helloworld4

oc delete project helloworld5

oc delete pv helloworld-pv

oc get pods --all-namespaces -o wide
----

== Conclusion

[discrete]
== End of Unit
link:../OCP-Workshop.adoc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
