:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Command Line Basics

The default and recommended method for interacting with the Openshift Container Platform is with the `oc` command.  In limited circumstances you could be directed to use other tools to invoke action or retrieve data from OCP, but for the most part all of your acitivities will be with `oc`.

== Check Cluster Status

.[root@master ~]# 
----    
oc status
----

.Your output should look like this
[source,indent=4]
----
In project default on server https://master.example.com:8443

https://docker-registry-default.cloud.example.com (passthrough) (svc/docker-registry)
  dc/docker-registry deploys registry.access.redhat.com/openshift3/ose-docker-registry:v3.9.33
    deployment #1 deployed 28 minutes ago - 1 pod
        
svc/kubernetes - 172.30.0.1 ports 443->8443, 53->8053, 53->8053

https://registry-console-default.cloud.example.com (passthrough) (svc/registry-console)
  dc/registry-console deploys registry.access.redhat.com/openshift3/registry-console:v3.9
    deployment #1 deployed 26 minutes ago - 1 pod

svc/router - 172.30.80.206 ports 80, 443, 1936
  dc/router deploys registry.access.redhat.com/openshift3/ose-haproxy-router:v3.9.33
    deployment #1 deployed 29 minutes ago - 1 pod

View details with 'oc describe <resource>/<name>' or list everything with 'oc get all'.
----
    
== High Level Cluster Check

.[root@master ~]# 
----
oc get all
----

.Your output should look like this
[source,indent=4]
----
NAME                                 REVISION   DESIRED   CURRENT   TRIGGERED BY
deploymentconfigs/docker-registry    1          1         1         config
deploymentconfigs/registry-console   1          1         1         config
deploymentconfigs/router             1          1         1         config

NAME                      HOST/PORT                                    PATH      SERVICES           PORT      TERMINATION   WILDCARD
routes/docker-registry    docker-registry-default.cloud.example.com              docker-registry    <all>     passthrough   None
routes/registry-console   registry-console-default.cloud.example.com             registry-console   <all>     passthrough   None

NAME                          READY     STATUS    RESTARTS   AGE                                                                 
po/docker-registry-1-zbwg2    1/1       Running   0          31m
po/registry-console-1-g669s   1/1       Running   0          30m
po/router-1-dxp2p             1/1       Running   0          31m

NAME                    DESIRED   CURRENT   READY     AGE
rc/docker-registry-1    1         1         1         32m
rc/registry-console-1   1         1         1         30m
rc/router-1             1         1         1         33m

NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                   AGE
svc/docker-registry    ClusterIP   172.30.235.25   <none>        5000/TCP                  33m
svc/kubernetes         ClusterIP   172.30.0.1      <none>        443/TCP,53/UDP,53/TCP     41m
svc/registry-console   ClusterIP   172.30.8.137    <none>        9000/TCP                  30m
svc/router             ClusterIP   172.30.80.206   <none>        80/TCP,443/TCP,1936/TCP   33m
----


== 2.7 Check Projects

.[root@master ~]# 
----    
oc get projects
----

.Your output should look like this
[source,indent=4]
----
NAME                                DISPLAY NAME   STATUS
default                                            Active
kube-public                                        Active
kube-service-catalog                               Active
kube-system                                        Active
logging                                            Active
management-infra                                   Active
openshift                                          Active
openshift-ansible-service-broker                   Active
openshift-infra                                    Active
openshift-node                                     Active
openshift-template-service-broker                  Active
openshift-web-console                              Active
----

== 2.8 Check Node Status

.[root@master ~]# 
----    
oc get nodes
----

.Your output should look like this
[source,indent=4]
----
NAME                 STATUS    ROLES     AGE       VERSION
master.example.com   Ready     master    1h        v1.9.1+a0ce1bc657
node1.example.com    Ready     compute   1h        v1.9.1+a0ce1bc657
node2.example.com    Ready     compute   1h        v1.9.1+a0ce1bc657
----

== 2.9 Check Pod Status

.[root@master ~]# 
----    
oc get pods
----

.Your output should look like this
[source,indent=4]
----
NAME                       READY     STATUS    RESTARTS   AGE
docker-registry-1-52lk5    1/1       Running   0          1h
registry-console-1-8qlb2   1/1       Running   0          1h
router-1-q92xl             1/1       Running   0          1h
----

== Gather Information About Cluster

NOTE: It can take considerable time and space to gather the output from the 'must-gather' command.  Please be sure your workshop environment is suited to support this acitivity.

To support debugging and troubleshooting issues, you can gather information from your cluster with a simple command.  Collection data includes:  

    * Resource definitions
    * Audit logs
    * Service logs

.[root@bastion ~]# 
----    
oc adm must-gather
----

The output is collected into a directory and can be 100+ MB in size.

== Conclusion

At this point it should be clear that the primary commandline interface to Openshift is the `oc` utility.
    
    
[discrete]
== End of Unit
link:../OCP-Workshop.adoc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
    
