:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[preface]
= Preface

This guide is intended to support a series of workshop exercises for individuals getting familiar with Red Hat's Openshift  Container Platform.

This is not an official Red Hat sponsered effort although I am currently employeed by Red Hat.  Rather this is a tool I use to teach myself and those I interact with professionally about new and emerging technologies.

In the spirit of Opensource, I am attempting to make my work publicly accessible for reuse by others.  But be advised that this is my first attempt at using GitHub and ascii-doc. So please be patient as I navigate my way through managing a day job while building out this project (workshop).  At some point I will stop editing in the master branch :-0

= Conventions Used

== Tips, Notes & Warnings

TIP: Extra info which could be helpful, but not essential for a given task or discussion

NOTE: Special information to pay attention

WARNING: Critical information which could help you avoid major set backs

== Executing tasks on the CLI

Each block of commands to execute will be label with the expected *user-id* and *host*.  To enhance cut & paste efficiency, the command prompt is omitted from each line.

.[root@master ~]#
----
oc get projects
----

== Output

Sample output will be titled with _'Your output should look like this'_ and also be indented to help with visual identification.  Sometimes there will also be footnotes and/or callouts.

.Your output should look like this
[source,indent=4]
++++
<em><pre>
NAME                                DISPLAY NAME   STATUS
default                                            Active
helloworld                          Hello World    Active
kube-public                                        Active
</pre></em>
++++

.Your output should look like this
[source,indent=4,emphasized]
----
NAME                                DISPLAY NAME   STATUS
default                                            Active
helloworld                          *Hello World*    Active // <1>
kube-public                                        Active
kube-service-catalog                               Active
kube-system                                        Active
logging                                            Active
management-infra                                   Active
openshift                                          Active
openshift-ansible-service-broker                   Active
openshift-infra                                    Active
openshift-node                                     Active
openshift-template-service-broker                  Active
openshift-web-console                              Active
----
<1> This is the line we are interested in with a special note

[discrete]
== End of Unit
link:../OCP-Workshop.adoc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
